### ISSUE TITLE
[Feature request] PiP mode on minimize

### ISSUE THREAD

**Issue by aexvir** [iina/iina#1442]
Hi!

I would like to suggest an option to trigger PiP mode when clicking on the minimize button of the window. I think that would be a very nice feature tu have. Also, let it be optional, for all the people who simply want the usual minimize behaviour.

Thank you very much!

**Comment by saagarjha** [comment]
Is there any reason why you'd like the minimize button to do this, specifically? Why not just use the shortcut for picture in picture, <kbd>⌘</kbd><kbd>⇧</kbd><kbd>P</kbd>?

**Comment by proudh0n** [comment]
@saagarjha Well, I'm someone that uses it a lot so I would prefer it triggering when clicking the minimize button instead of having to use always the shortcut. I think it could be nice to have.

**Comment by lhc70000** [comment]
In v1.0, you'll be able to add a button to trigger PIP in the on screen controller (OSC). Does this solve your problem somehow?

**Comment by fabi94music** [comment]
when will v 1.0 be released?

**Comment by lhc70000** [comment]
@fabi94music If you want to try this feature as soon as possible, plese upgrade to 0.0.15 build 68 (just released) and choose "receive beta updates".

**Comment by fabi94music** [comment]
awesome ! 👍

**Comment by proudh0n** [comment]
@lhc70000 Maybe. I only wanted the minimize button for convenience. It's easier to click the minimize button, which is the same on all apps than finding another button on the OSC. Also it doesn't seem to me a difficult request (correct me if I'm wrong, I'm no cocoa developer). I think I'll still prefer the minimize button, but I'd like to see the OSC button.

I've activated beta updates so as soon as is implemented I'll comment on this issue.

Thank you very much!

**Comment by fullmetalsheep** [comment]
@aexvir 

Hi, I found a easy workaround for you since this seems feature request looks a bit subjective.
You'll need **BetterTouchtool** to implement this. Setup the shortcuts similar to the screenshot below:

![6ad6d37f-c363-475b-bd09-60fb560e520d](https://user-images.githubusercontent.com/23723926/46386584-dbfe5c00-c6f4-11e8-862a-7a3e6cf75e61.png)

Here is the above shortcut in action:

![2018-10-03 10 14 34](https://user-images.githubusercontent.com/23723926/46386646-3f888980-c6f5-11e8-8853-11aed88329ca.gif)
