### ISSUE TITLE
New design of preference window

### ISSUE THREAD

**Issue by alejx** [iina/iina#1870]
In 1.0.0 beta 3, we added a newly designed preference window. Although that the previous one works fine, but 
1. We were using [MASPreference](https://github.com/shpakovski/MASPreferences), which is a fairly old framework, and does not seem to update recently.
2. Customizing the preference window using the framework is very hard.
3. Inevitably, more settings and features will be added into IINA, but the old design was already very crowded.

So we decided to drop MASPreferences and create one ourself. One feature we added into the preference window is the ability to search amount all of the settings (which is not easy to do using MASPreferences).

However, this is the first version since the new preference window debuts, we should polish and redesign some of its part. You are welcome to comment your opinions and thought about the new design here.

**Comment by fabi94music** [comment]
One the subtitles submenu in the German version there seems to be a layout problem.

**Comment by LeoNatan** [comment]
I agree about the design not fitting the overall system UX. iina set out to be as much macOS looking as possible, and I think this is what attracted so many people to the project, which is great! But reinventing such a fundamental UX pattern for something custom is not a good idea.

Regarding search, instead of a custom search field, you should implement [NSUserInterfaceItemSearching](https://developer.apple.com/documentation/appkit/nsuserinterfaceitemsearching?language=objc) and let users search for options in the Help menu.

**Comment by jerkstore369** [comment]
As a regular user of IINA I want to say that I like the older preference window looks. I don't understand how anyone can get lost in it. If you don't see what you want go to the next tab and so forth. It doesn't take much time at all to learn where all the preferences are. Not being good for other languages doesn't seem like that good of a reason to do a redesign. You're saying the tab sizes can't just be increased in width to fit words that take up more space in other languages? Even so, can't you use short hand? Also, again, like I mentioned, once someone finds where something is simply by digging around in the preferences, then all is good anyways.

**Comment by pleasejust** [comment]
I take everything back. The new preferences window actually looks ok. People will get used to it eventually anyways.
