### ISSUE TITLE
Unsupported external subtitle for .ass without [Script Info]

### ISSUE THREAD

**Issue by v3i1r4in** [iina/iina#2124]
I have some .ass subtitles that is said unsupported. I have inspect the content of my ass files and I found the problem is that they are missing the `[Script Info]` at the beginning of the script. I have no problem playing these ass files in other players (MPlayerX). I wonder if you can make IINA to tolerate them as well?

**Comment by inflation** [comment]
Please report it to libass. mpv uses it to process ass files, and so does IINA.

**Comment by astiob** [comment]
mpv doesn’t use libass to parse standalone ASS files (since 2015), only to render their contents. As noted in mpv-player/mpv#2846, this appears to be an issue with FFmpeg’s [`ass_probe`](https://github.com/ffmpeg/FFmpeg/blob/master@{2019-01-07}/libavformat/assdec.c#L36-L51), which rejects all files that don’t start with `[Script Info]` optionally preceded by a number of blank lines.
