### ISSUE TITLE
The texture on the red color seems blurry.

### ISSUE THREAD

**Issue by ty-cs** [iina/iina#2255]
**System and IINA version:**

- macOS 10.14.3
- IINA 1.0.1 Build 103 (mpv 0.29.1)

**Expected behavior:**
On mpv:
![mpv](https://user-images.githubusercontent.com/18642966/51786323-8d8e3500-219d-11e9-945f-0fecd37d0046.jpg)

**Actual behavior:**
On IINA (the red hair part seems blurry compared to mpv):
![iina](https://user-images.githubusercontent.com/18642966/51786324-8d8e3500-219d-11e9-80e7-b77f0603265b.png)

**Comment by alejx** [comment]
Did you enable hardware encoding?

**Comment by lty96117** [comment]
@alejx It was `Auto`
<img width="899" alt="xnip2019-01-31_12-34-00" src="https://user-images.githubusercontent.com/18642966/52030810-87f56e00-2554-11e9-8ad3-9eb917e2d529.png">

**Comment by alejx** [comment]
This might be related to hardware decoding. Please refer to https://github.com/mpv-player/mpv/issues/6369

**Comment by kyoukai82** [comment]
I can confirm that this issue is produced by opening an mkv file that contains bright red (or magenta) colors resulting in chroma artifacts along the edges of the red/magenta. However, this issue only occurs with mkv files that are encoded a certain way are played back with IINA (I don't specifically know but HEVC encoding does seem likely). For example, try finding "smallcoded" anime online (eg. animechiby (no issue), animekayo (red chroma issue) that contains bright red (Rias Gremory's hair for an example experiences this issue when encoded in a certain way) and you will see its caused by IINA's decoding settings (possibly).

I think this might be an issue with how IINA "upscales" or "high definition-ify" videos (or decodes videos) as IINA's video playback of the same source seems the most "clean and high quality" while other players video playback isn't as clean but no red/magenta chroma artifacts are seen (see attachments). This issue is still present in both hardware decoding on and is sometimes present when it is off.

Red Chroma Artifacts (easier to see example):
![](https://user-images.githubusercontent.com/30968227/59392286-6f2a7e00-8dba-11e9-80e1-7eff491a054a.jpg)

Magenta Chroma Artifacts:
<img width="2560" alt="Senran Kagura" src="https://user-images.githubusercontent.com/30968227/59825016-26ecfc00-9376-11e9-857a-86c9b1671374.png">

I don't know if the results/code from similar issue [https://github.com/mpv-player/mpv/issues/6546](url) will help resolve this issue or not.

**Comment by inflation** [comment]
@kyoukai82 If you still experience the same problem after manually disabling hardware decoding, it would be another problem, as said in that issue. 

Also, there are lots of things to tweak regarding to upscaling or downscaling (algorithm, chroma, etc.), so for the record, IINA uses the default mpv settings, e.g., bilinear for all. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
