### ISSUE TITLE
Media Keys Not Working On App Starts Up.

### ISSUE THREAD

**Issue by nuynait** [iina/iina#2338]
**System and IINA version:**

- macOS 10.14
- IINA 1.0.2 Build 105

**Expected behavior:** Media key should control IINA to play or pause

**Actual behavior:** Open IINA with a video, press play button opens iTunes.

To make media key work, I will have to open IINA with a video, press space twice and then press system media button can control the video. 

The `Use system media control` is enabled under Key Bindings. 

I have read through a lot of tickets related to media keys, and none of them experience something like I did. So I believe this ticket is not duplicated.

**Comment by nuynait** [comment]
So if I open IINA with a video and then close the video using (CMD-W) instead of (CMD-Q) then if I open another video, the media key can be used right away without press space twice.

**Comment by saagarjha** [comment]
This is how the macOS Media Player API works, AFAIK. We might be missing a call to acquire video focus (if there is such a thing, @alejx probably knows more about this), but if you don't video focus you will have to actively interact with the player to get it back.

**Comment by LEoREo2247** [comment]
Media keys just works perfectly on older versions, but not on v1.0.2 release.

IINA seems to be grabbing media key presses using MPRemoteCommandCenter, but in order to make this work, we first need to set the playback state of MPNowPlayingInfoCenter to .playing. Which in the previous version, the initial playback state in was set to .playing after setting up CommandCenter, but I can see that it's changed to .unknown in v1.0.2.

I guess this is the reason why that media keys won't work until users pause and play manually to re-set this state.

While we should keep this unknown as it may grab the media control event even while the app is playing nothing, playback state needs to be set to playing at some point before the media playback starts?

**Comment by alejx** [comment]
Sorry for my silly mistake, will fix it soon.
