### ISSUE TITLE
[Feature request] Is it possible to save a video stream?

### ISSUE THREAD

**Issue by lolgear** [iina/iina#2351]
**System and IINA version:**

- macOS 10.13.6
- IINA  1.0.2

**Expected behavior:**
I expect that video player has an option to save video cache into a file.

**Actual behavior:**
I can't find this option or I am blind, please, show it.

Thanks!

**Comment by lhc70000** [comment]
Sorry but not now, since it's only [an experimental feature in mpv](https://mpv.io/manual/master/#options-record-file), and it's expected to be fragile and unstable (like what if you skipped during playback?).

Supporting this option in the main IINA application is not in the plan, but if you really want, hopefully it can be implemented via a plugin when the plugin system is ready.

**Comment by mehulkatpara** [comment]
Can you please have this implemented as a plugin at least? 
I have been using this player for almost 6 months, even to watch YT videos. It would be nice to download the streamed videos so you can always go back to lectures and re-learn them instead of going back and forth on YT all the time. 

Thank you very much. :) 🥇
