### ISSUE TITLE
Fast Forward Text Bug and Button Suggestion

### ISSUE THREAD

**Issue by MadhavChoudhary** [iina/iina#2390]
## Versions
macOS 10.14.4
IINA 1.0.3 Build 106 (mpv 0.29.1)

### Bug
After Pressing the fast forward button, a text `2x` appears to the right side of it. If it is changed back to '1x' from the settings, the `2x` still remains there, until we pause and resume the video. Same goes for Slow Forward Button (or should I say slow backward, since it is pointing backwards? but the video is not actually going backwards, which I personally like!). 
This is just a small bug. 

### Suggestion
And I think It would be better to have a the Slow Forward arrow reversing the effect of Fast Forward Arrow, for ex, when you press `2x`, then want to go back to `1x`, pressing the backward arrow to nullify the effect of the forward arrow would be more intuitive than to pause and play the video. 
Now, when I press the backward arrow, it goes to `0.5x` straight from '2x` or `4x`

**Comment by alejx** [comment]
I'm pretty sure that we referred to QuickTime's fast forward and rewind buttons when we design the these two buttons. If you first fast forward then press the rewind button, it will instantly rewind, instead of slow down the fast forward. **But** we are not rewinding like QuickTime, so I agree @MadhavChoudhary's opinion. It's weird to jump from 4x fast forwarding to 0.5x.

cc @saagarjha @lhc70000

**Comment by saagarjha** [comment]
Relevant pull requests, with some background behind the behavior: #111, #116. I'm mildly in favor of changing this, though.
