### ISSUE TITLE
After exiting pip mode the video content is not displayed in the IINA window

### ISSUE THREAD

**Issue by xjbeta** [iina/iina#2719]
**System and IINA version:**

- macOS 10.15.2 (19C57)
- IINA 1.0.5 / develop branch 86a4cad

**Steps to reproduce:**
1. enter pip mode 
2. click **X**  exit pip mode
3. Video content is missing

**Comment by anohren** [comment]
I thought I was alone in this in my custom build. I set a lot of breakpoints but ultimately couldn't determine what I was missing.

Does your window show the "playing in pip" message after clicking X?

Some speculation on my part is that since noone else seems to have experienced this until 1.0.5 it should be a change that's in common with my build. The only thing I can think of straight away is having disabled advanced rendering.

**Comment by anohren** [comment]
> having disabled advanced rendering

It wasn't that. Oh well.

**Comment by anohren** [comment]
I isolated the problem to 425f221bae689054d1056ce63d6017246158166b
