### ISSUE TITLE
MacOS error

### ISSUE THREAD

**Issue by davincism** [iina/iina#2735]
When I start IINA, there is the alert every time. But IINA works.
![image](https://user-images.githubusercontent.com/36439553/72744075-3d02b980-3bf0-11ea-90b7-388fe2bc9283.png)

**Comment by Tsubajashi** [comment]
Do you use advanced mpv Settings? I cant speak your language, but i think its that.

**Comment by davincism** [comment]
@Tsubajashi I don't use advanced mpv. My all of setting values are default.

**Comment by alejx** [comment]
Did you enable "initial window size" or "initial window position"? Can you try to disable them and see whether the issue exists?

**Comment by davincism** [comment]
@alejx I just disabled them, and it works! Thanks a lot! By the way what's the reason?

**Comment by lhc70000** [comment]
The reason is unknown for now. It might be a rare bug (that's why we suggested you running that command before to gather more information). Anyway, if it happened again, disabling and enabling the "initial window size" option should work (it resets the internal value). We are also considering adding some validation to prevent this issue in the future.
