### ISSUE TITLE
1.0.5 and 1.0.6 always plays from the beginning

### ISSUE THREAD

**Issue by erujp** [iina/iina#2736]
Mac OS 10.15.2. Before 1.0.5, when I started playing a video it always started from the last playing position, but with version 1.0.5 and 1.0.6 every file always starts from the beginning. So I just downloaded 1.0.4 again and, without touching any option, now it plays from the last position again.

**Comment by nicolasonline** [comment]
Having the exact same issue. macOS 10.15.2 IINA 1.0.6 on a late 2013 MacBook Pro 15"

**Comment by inflation** [comment]
Weird. Do you have any log when this happens?

**Comment by moviec** [comment]
Preferences->General
Uncheck "Quite after all windows are closed"
It seems to work.

**Comment by erujp** [comment]
> Uncheck "Quit after all windows are closed"
> It seems to work.

Thank you, I confirm that this works, but… it's not an ideal solution. It would be nice to have the possibility to use the "Quit after all windows are closed" option too, as until version 1.0.4

**Comment by inflation** [comment]
Hmmm. I suppose it is because when you close the window, IINA saves the last playing position to a file in one thread. Then it triggers quitting in the main thread, which terminates all other threads before the operation finishes.

**Comment by low-batt** [comment]
IINA's `Resume last playback position` feature uses mpv's [watch later](https://mpv.io/manual/stable/#watch-later) feature.

@inflation correctly identified the issue, a [race condition](https://en.wikipedia.org/wiki/Race_condition#In_software) between threads when IINA terminates. That has been corrected and IINA 1.3.1 waits for mpv to finish before terminating. Unfortunately that brought out other problems with coordinating shutdown. Those problems have been fixed in the development version of IINA. Work is in progress on a new release.
