### ISSUE TITLE
8k YouTube not working

### ISSUE THREAD

**Issue by gferreroferri** [iina/iina#2740]
With latest version of Iina in latest version of macOS, when I try to open an 8K YouTube link, the app does not do anything

**Comment by inflation** [comment]
YouTube is using new `av1` codec for their 8k contents. Unfortunately, `mpv` does not have the codec support by default due to its lacking of optimization (basically makes your CPU on fire). What you can do is set `youtube-dl` options like this:
![image](https://user-images.githubusercontent.com/2375962/73999051-86ae0c80-4931-11ea-98ea-f9aadc92ae07.png)
However, since `vp9` is not hardware decodable either, beware that it would make your CPU hurt.
