### ISSUE TITLE
Speed rate input should not be letters or emojis

### ISSUE THREAD

**Issue by raghav4** [iina/iina#2789]
**System and IINA version:**

- macOS 10.15.3
- IINA 1.0.6 Build 113

**Expected behaviour:**

The speed rate input should only let numbers as
 input.

**Actual behaviour:**
We could enter both the emojis and letters as an input.

<img width="333" alt="Screenshot 2020-02-29 at 12 47 07 AM" src="https://user-images.githubusercontent.com/20716185/75580035-08a2d880-5a8d-11ea-9123-1500bd76066e.png">

**Steps to reproduce:**

* Go the settings 
* Enter the letters/emojis

- [x] MPV does not have this problem.

**Comment by anohren** [comment]
What kind of problem does this cause?

Why should it not allow letters, and what should happen when you try to input them?

**Comment by raghav4** [comment]
* It doesn't cause any problem as such but while entering a number if a letter is printed by mistake it doesn't work. 

* It should not allow letters as the **video speed can never be a letter**, will it be?
> what should happen when you try to input them?

* We should not be able to enter any 'unexpected' character into it.

**Comment by saagarjha** [comment]
Are you telling me you don't watch videos at 1😩ss speed?

**Comment by anohren** [comment]
Thanks

>     * It should not allow letters as the **video speed can never be a letter**, will it be?

The video speed cannot be a letter, but I don't think that is good enough reason to prevent users from entering them after having presented the user with a free-form text field. The affordance of a text field is clear (anything goes), and it's the developer's job to work around its drawbacks after choosing to use one, instead of imposing restrictions on its functionality and thereby cause mismatch between user expectation and what's "allowed". For instance, if I have "1,5" in my clipboard, I would be _disallowed_ from pasting it in the text field if my locale imposes a `.` decimal separator and not a `,`. 

The text field already complains that the input isn't valid when you try to shift focus away from it; validation does occur.

**Comment by saagarjha** [comment]
Jokes aside, we're using a number formatter for that field already. The system behavior for these is to allow invalid characters and then perform validation.

**Comment by raghav4** [comment]
@anohren okay! I get it

**Comment by raghav4** [comment]
@saagarjha, cool!

**Comment by saagarjha** [comment]
Closing, unless someone has objections that this should be reopened.
