### ISSUE TITLE
IINA subtitles disappear when toggled

### ISSUE THREAD

**Issue by fyreswan** [iina/iina#2859]
IINA has been working with subtitles for me, with no problem. When I have tried to toggle the subtitles on and off, suddenly the subtitles do not work at all on any video I play, when they were working fine 1 hour ago. I was able to toggle them without troubles yesterday. I have not updated IINA or any other program.

On 1.0.7-beta1 Build 115, and I have been for a while.

**Comment by fyreswan** [comment]
I managed to fix this by resetting all the settings and re-downloading IINA.

**Comment by fyreswan** [comment]
It has just started again and clearing all the settings does not fix it.

**Comment by lhc70000** [comment]
Lots of users encountered this problem because they triggered the shortcut for hiding subtitles accidentally. You can look up shortcuts in Preferences - Keybindings and check the current status of `sub-visibility` by adding it into the "Watch" section in the inspector:

![image](https://user-images.githubusercontent.com/8478049/78992270-70a90c00-7b6d-11ea-8cc5-528905889351.png)

Running "Clear saved playback progress" in Preferences - Utilities may also help.

If these don't work, please provide logs (Utility - Advanced - Enable logging).

**Comment by fyreswan** [comment]
Thank you, this was exactly the problem! The solution is simply to press "V" to see the subtitles again.
