### ISSUE TITLE
[Just a question] An option to have permanently static window size and position, despite video size?

### ISSUE THREAD

**Issue by yuriy-zenfolio** [iina/iina#2882]
Hello, I used PotPlayer for Windows for ages and it was a perfect player, but recently I migrated to MacOS, and there is no way to use it anymore. I find IINA best alternative, everything works just amazing, thanks for that. 

But only one annoying kind of issue: the app window always resizes in accordance with video resolution and there is no option to fix this behavior (or I cannot find it). I played with the options **"UI" -> "Window" -> "Resize the window to fit video size"**, but, actually, there is no significant difference between them. When I switch between videos with different aspect ratios using key shortcuts the window still resizes and moves chaotically.

I don't care about black strips on the top and bottom, or left and right, I just want the app window to be in the same place with the same size. 

As far as I understood, MPV which IINA based on is able to do that with the parameter **--no-keepaspect-window**. I tried to use it in IINA with mvp.conf file, but it seems it doesn't work. A bit later I found next info on the "MPV Options and Properties" page:

> **keepaspect** 
> IINA’s window will always keep with video’s aspect. This property is true in windowed mode and false in full screen.

Why cannot I set up this property? Is this a MacOS limitation? Or, maybe there is an another option or set of options to have permanently static window size, despite video size?

Thank you.

**Comment by lhc70000** [comment]
It’s in the plan, please stay tuned.

**Comment by yuriy-zenfolio** [comment]
@lhc70000, thank you for informing. 
Keep doing the amazing work!

**Comment by qmarsn** [comment]
5 years later, still no option for no-keep-windowaspect.

**Comment by NotImportant1116** [comment]
5 years later and this still has not been fixed. No real point in still using IINA anymore

**Comment by qmarsn** [comment]
My comment was a little passive aggressive. I most certainly appreciate the work that the devs have put into IINA and giving us a free and awesome video player. I was just a little disappointed to see that something that seems a pretty easy implementation (since MPV is already doing it on mac).

I might be out of line here and its not a easy implementation but I just don't know how it wasn't something that was not slated into a release after seeing reports about it since 5 years ago.

**Comment by Brunni132** [comment]
If I may add to this, I think that it would make a lot of sense to keep the window size when switching from videos in a playlist. Actually, I would even say that I don't really see when a user could expect the window to be resized between each file from a playlist.

I was also surprised because I expected this option to be perfect for my use case, but it turns out that has no effect. It's a bug, is it?

![Image](https://github.com/user-attachments/assets/eb2c5f23-14c9-4fb1-80a2-697c97812b68)

**Comment by qmarsn** [comment]
Sorry to be the bearer of bad news" but its not a bug. its just how the player behaves despite you giving clear directions on what it should do. pretty frustrating that it STILL doesn't do such a basic task/window size behavior.

**Comment by Brunni132** [comment]
Yeah that must be frustrating, and it would be great to have an official answer about the reasoning behind this. It's otherwise an amazing player.

**Comment by lcolen** [comment]
I've been running up against this in IINA myself.  It had been working fine for me, then I did an upgrade and now every time it changes the video file it resizes the window.

**Comment by surajmandalcell** [comment]
Almost at the end of 2026 Still does not behave the way regular vlc worked. Jarring when I have to move through multiple files and it keeps changing window wize.
