### ISSUE TITLE
Use number pad to move through video 1=10%, 5=50%, 9=90%, etc...

### ISSUE THREAD

**Issue by joshkerr** [iina/iina#2936]
**What you want IINA to do:**

I'd like to be able to use the number pad to quickly jump to a % of the video. So 1 would jump to 10% location in the video. 7 would jump to 70% location in the video. etc..

**What IINA does currently:**

It does nothing when I press the numbers.

**Why you think this should be added:**

Faster way of moving through videos. This is really useful for youtube videos especially.

**Examples of other projects that have something similar:**

YouTube via the web does this.

**Comment by lhc70000** [comment]
Please try adding new key bindings in Preferences:

https://github.com/iina/iina/wiki/Manage-Key-Bindings#key-bindings

You may choose "seek" "to" * "%" as the action.

Please reopen this issue if any error occurred, such as IINA failed to record the button. I currently can't test it because none of my keyboards have a number pad.
