### ISSUE TITLE
Mouse scroll is off but still causes seek when touching mouse

### ISSUE THREAD

**Issue by edrozenberg** [iina/iina#2996]
**System and IINA version:**

- macOS 10.14.6 (18G5033)
- IINA 1.0.7 Build 119

**Expected behavior:**
When Control->Scroll vertically to: NONE, Scroll horizontally to: NONE
Expect no seeking at all when touching mouse surface

**Actual behavior:**
While mouse cursor is inside the video control box (play/pause etc), scrolling horizontally causes seeking to happen. It's a Magic Mouse, and it's maddening for obvious reasons when accidental touches on the mouse surface cause the video position to change. Really want no seeking at all when the prefs are set to NONE.

Issue present in IINA for some time.

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

Set IINA prefs Control->Scroll vertically to: NONE, Scroll horizontally to: NONE
Do mouse horiz scroll while pointer is inside video control box

- [ ] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by alejx** [comment]
This is intended. To be accurate, only if you scroll your mouse (or trackpad) inside the sliders, both the progress scroller and the volume scroller, the video will seek or adjust the volume accordingly. 
![image](https://user-images.githubusercontent.com/20237141/84894684-c355f580-b0d3-11ea-950e-d338dad12178.png)
If you try to scroll your mouse here, this volume scroller will change as well. So the settings in IINA 
do not change the behaviors when your mouse is on top of the scrollers.

**Comment by edrozenberg** [comment]
I see, so this is MacOS letting the mouse control any slider. The video position scroller then is also considered by the OS to be a slider that the mouse can modify. Nothing IINA can do about it. Thanks.

**Comment by anohren** [comment]
> only if you scroll your mouse (or trackpad) inside the sliders, both the progress scroller and the volume scroller, the video will seek or adjust the volume accordingly

This is not true for me.

I think this issue should be reopened, because of the following:

1. When the interface layout is set to *Top*, you cannot control these sliders by scrolling. This is a workaround for you, @edrozenberg. It is also a bug.
2. When using Floating or Bottom layout: if you start precision scrolling (e.g. using the touchpad) inside the on-screen controls' box but outside of one of the sliders, then release the scrolling mid-gesture to preserve scrolling inertia, and subsequently move the cursor over either slider then you'll affect them. You'll potentially adjust both sliders with a single scroll gesture that wasn't initiated while hovering over either.
3. If you encourage users to hover over the timeline with thumbnail previews you'll probably want to make an effort to avoid accidental time jumps like this, since there is no undo. I don't have a magic mouse, but I imagine the fingers are resting on the scroll surface. It is reasonable to at least consider disabling scrolling for the timeline slider as well, as an advanced option if necessary.

> Nothing IINA can do about it.

There is.

**Comment by Erik262** [comment]
Same here, it is very annoying when I want to select a specific place in the timeline bar or whatever it is called, and If I got a little bit sidewise with my finger it starts scrolling.
