### ISSUE TITLE
First screenshot always fails

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [iina/iina#3163]
**System and IINA version:**

- macOS High Sierra
- IINA 1.1.0 Build 123

**Expected behavior:**

Keybind create a screenshot in a given directory.

`screenshot video ; set screenshot-directory /Users/blablabla`

**Actual behavior:**

No screenshot is created the first time the key is pressed. Every time after that, a screenshot is indeed created in the given directory.

**How often does this happen?**

Always, and only since some recent version of IINA. I've been using this same keybind for years.

**Comment by dmattera** [comment]
I could be wrong but I think you just to flip the order of those two commands to:

```set screenshot-directory /Users/blablabla ; screenshot video```

My guess is that using the commands in the order that you have them, the first screenshot you take is being saved to whichever default folder you have set in the IINA preferences > General > Screenshots which is maybe different from the folder you are setting in the command (```/Users/blablabla```). then after you run your command the first time, the screenshot folder is being set to ```/Users/blablabla``` and subsequent screenshots will save there instead of the IINA default folder.

**Comment by 2V3EvG4LMJFdRe** [comment]
Strange. I don't have the "Save to" destination checkbox marked, but your suggestion worked. Thanks.
