### ISSUE TITLE
Crashes on 10.11 when opening URLs

### ISSUE THREAD

**Issue by 097115** [iina/iina#3327]
**System and IINA version:**

- macOS 10.11
- IINA 1.2.0-1.1.1

**Expected behavior:**
Should not crash.

**Actual behavior:**

    IINA 1.2.0 Build 129
    2021-02-17 07:21:41.453 iina[68301:410911] Could not connect action, target class IINA.MainWindowController does not respond to -additionalInfoTitle:
    dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
      Referenced from: IINA.app/Contents/MacOS/../Frameworks/libgnutls.30.dylib
      Expected in: /usr/lib/libSystem.B.dylib
    
    dyld: Symbol not found: _clock_gettime
      Referenced from: IINA.app/Contents/MacOS/../Frameworks/libgnutls.30.dylib
      Expected in: /usr/lib/libSystem.B.dylib
    
    Trace/BPT trap: 5

Some relevant discussion: https://github.com/pocoproject/poco/issues/1453#issuecomment-254663587

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
To workaround this you should install [legacy-support](https://ports.macports.org/port/legacy-support/) and [yt-dlp](https://ports.macports.org/port/yt-dlp/) (because build-in youtube-dl is obsolete) via Macports and run this code in terminal:
```
sudo rm /Applications/IINA.app/Contents/MacOS/youtube-dl
sudo ln -s /opt/local/bin/yt-dlp /Applications/IINA.app/Contents/MacOS/youtube-dl
sudo install_name_tool -change /usr/lib/libSystem.B.dylib /opt/local/lib/libMacportsLegacySystem.B.dylib /Applications/IINA.app/Contents/Frameworks/libgnutls.30.dylib
```
![2021-12-20_21-47-17](https://user-images.githubusercontent.com/69355938/146817672-3a763718-c17d-412c-ae53-1a9a62961900.png)

**Comment by 097115** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou , Thanks :)

**Comment by low-batt** [comment]
@097115 Was this closed because installing [legacy-support](https://ports.macports.org/port/legacy-support/details/) as a workaround eliminated the crash for you (thank you @aeiouaeiouaeiouaeiouaeiouaeiou)? Great to have a workaround, but I'm thinking this is still a valid IINA problem and needs to be re-opened. At the very least IINA should document this issue and a workaround in the release notes.

The analysis of the issue in the posts above and linked references looks correct to me. The `clock_gettime` function was not added to macOS until 10.12 as documented in the man page (under newer versions of macOS):
```text
low-batt@gag ~$ man clock_gettime
...
HISTORY
     These functions first appeared in Mac OSX 10.12
```

This legacy-support page [MacPorts Support for Legacy OSX Versions](https://github.com/macports/macports-legacy-support) confirms legacy-support supplies a wrapper for `clock_gettime`:
| Header File | Feature | Max Version Needing Feature |
| --- | --- | --- |
 | time.h |	Adds clock_gettime function (macOS10.11). Declares asctime_r, ctime_r, gmtime_r, and localtime_r functions that are otherwise hidden in the presence of _ANSI_SOURCE, _POSIX_C_SOURCE, or _XOPEN_SOURCE (OSX10.4) | OSX10.4(11) |

IINA correctly sets `MACOSX_DEPLOYMENT_TARGET` to `10.11` when building the libraries with homebrew. And the build for the GnuTLS library checks to see if `clock_gettime` is available in [gnutls / configure.ac](https://github.com/gnutls/gnutls/blob/master/configure.ac):
```text
AC_LINK_IFELSE([AC_LANG_PROGRAM([#include <time.h>], [clock_gettime(0, 0);])],
  [AC_MSG_RESULT(yes); ac_cv_func_clock_gettime=yes
  AC_DEFINE([HAVE_CLOCK_GETTIME], 1, [Define to 1 if you have the `clock_gettime' function.])],
  [AC_MSG_RESULT(no); ac_cv_func_clock_gettime=no])
```

Trouble is `AC_LINK_IFELSE` is able to access `clock_gettime` even when building for macOS `10.11`. I have confirmed that a tiny test program that calls `clock_gettime` still works when compiled with  Xcode 13.2.1 and setting macOS 10.11 as the macOS Deployment Target in the build settings. Xcode only emits a compilation warning.

In one of his posts to this issue [xz broken on OSX 10.11.6 Beta (15G24b) with XCode 8 Beta](https://github.com/Homebrew/homebrew-core/issues/2674) jeremyhu from Apple explains why:
>This isn't a bug with the SDK. The availability macros correctly cause clock_gettime to be weak when you set a deployment target of 10.11.

This behavior is not expected by many `Autoconf` templates.

I still see references to `clock_gettime` in a recent build of the dependencies:
```text
low-batt@gag lib (develop $=)$ nm  libgnutls.30.dylib | grep clock_gettime
                 U _clock_gettime
```

I don't have a macOS 10.11 setup to test with. I'd guess this issue would be a problem for downloading subtitles and checking for updates.

**Comment by 097115** [comment]
@low-batt,

Thanks for the insight, I will re-open the issue, but since I'm no longer using IINA (and my old macOS 10.11 is now miles away), I probably leave it up to devs to keep the issue either opened or close.

Thanks again.
