### ISSUE TITLE
UI: Appearance setting is ignored, always set to Match System Appearance

### ISSUE THREAD

**Issue by ADemkin** [iina/iina#3436]
Hello,

i found that UI -> Appearance: -> Theme: setting is completely ignored. Whatever setting is selected (Light, Dark) it is always work like "Match System Appearance". If i set IINA ui to "Dark", but macOS ui to Light, then IINA set Light theme. If i set Light in IINA, but Dark in macOS, then IINA goes Light. So it looks like this setting is totally ignored.

**System and IINA version:**

- macOS Catalina 10.15.7
- IINA 1.1.2 Build 128

**Expected behavior:**
IINA keep UI theme based on selected theme it its preferences, even if it does not match macOS theme.

**Actual behavior:**

IINA always match UI theme to current macOS theme.

**Steps to reproduce:**
Set macOS theme to Dark. Set IINA theme to Light. IINA will be Dark.
Set macOS theme to Light. Set IINA theme to Dark. IINA will be Light.

**How often does this happen?**
Always.

**Comment by low-batt** [comment]
This setting is working for me, **but** it is only applied to the player windows, UI elements such as the preferences window, history window, etc., continue to reflect the macOS systemwide appearance setting. I'm guessing it is this way because you can't apply an appearance at the application level until macOS 10.14 (Mojave). Earlier macOS versions require more code to support this. I'm guessing the implementation prioritized getting this to work for the player windows and keeping the behavior consistent across all macOS versions as a first phase, planning to eventually implement support for other UI elements. But that is just me guessing at the history of this feature. 

I'm proposing that for this feature we allow IINA behavior to differ across macOS versions and fix this for macOS 10.14 and above by setting the appearance at the application level.

The fix in the pull request will change AppDelegate.applicationDidFinishLoading to set the appearance at the application level based on the IINA preference and establish an observer to watch the preference for changes and update the appearance as needed. The appearance is only set when running under macOS 10.14 and above.

To minimize changes for this fix the existing code that sets the appearance at the windows level was not updated to only set the appearance when running under macOS 10.13 and below.

Thoughts? Critical reviews including criticism of style and naming are welcome.

If reviewers want the existing window level code to be updated to only be used for macOS 10.13 just let me know and I will add that cleanup to the commit.

**Comment by saagarjha** [comment]
This behavior is intentional; the reasoning behind it being that UI chrome should match the system appearance like the rest of the OS but the experience of watching a video is something that is disjoint from what the system looks like at moment. (Specifically, we think that most IINA users prefer using the dark appearance for the video player.) We're open to discussion about this choice but I'm going to close this for now, and it'll stay closed unless a good argument is presented for the other side.
