### ISSUE TITLE
Upgrade mpv to 0.33.1 to fix security vulnerabilities

### ISSUE THREAD

**Issue by orlando-oli** [iina/iina#3472]
IINA currently uses mpv 0.32.0; this is unadvised since CVE-2021-30145.
**What you want IINA to do:**
Upgrade mpv shipped with IINA to 0.33.1
**Why you think this should be added:**
For security reasons.

Source: https://github.com/mpv-player/mpv/releases/tag/v0.33.1

**Comment by HarukaMa** [comment]
Confirmed the format string vuln is present.

Dunno if hardened runtime could prevent code execution and the attacker need to specifically target macOS C libraries to execute any meaningful attack, but crashing the player is trivial.

**Comment by low-batt** [comment]
This IINA issue:

Leaking "advanced_editlist objects, #3460

Could be fixed when upgrading to mpv 0.33.1 by applying a patch to include this two line commit from the mpv master branch: [demux_lavf: fix minor memory leaks](https://github.com/mpv-player/mpv/commit/f665149fc889724ab011b6839f17568b1e9c69d0)


This IINA issue:

Leaking memory related to mvp/Lua, #3463

Will likely be fixed by the upgrade to mpv 0.33.1.

**Comment by gerardp** [comment]
This bug is so important that it is necessary to release a new version as soon as possible.

**Comment by low-batt** [comment]
The instructions in the README for building mpv manually include running `other/parse_doc.rb` to regenerate the sources `MPVOption.swift`, `MPVCommand.swift` and `MPVProperty.swift`. At this time the `MPVProperty.swift` generated by the script fails to compile. I have reported this in issue #3494. I have also submitted a pull request that updates the script to correct this issue.

I've also submitted pull requests in the homebrew-mpv-iina repository for various changes required to update the build to use mpv 0.33.1.

When creating an IINA build with mpv 0.33.1 to address this security issue it would be good to include merging the pull request associated with issue #3472 as that PR updates the displayed copyright to reflect 2021.

There are many other outstanding PRs that contain fairly simple changes that fix defects reported multiple times. For example the proposed fix for issue #3159 is a one line change. Some of these maybe simple enough to include in a build that addresses this security issue.

**Comment by gerardp** [comment]
@low-batt you should be the maintainer of the project.
Or better, make a fork of iina and create a new project.

**Comment by low-batt** [comment]
Thanks for the vote of confidence, but if IINA was a corporation looking to hire developers they would look at my resume and quickly deem me "not even worth a phone screen". I have lots of experience with many different software technologies, none of which are being used by IINA. IINA is all about the user interface. To begin with a developer should be an expert macOS graphical user interface application designer and coder. I've never worked on UIs, never mind the macOS Cocoa frameworks.

I am experienced at digging into software to find the root cause of a defect. As good as IINA is, if you look through the issues you will find multiple defects that have been reported several times by users. IINA could definitely benefit from a bug swatting release that corrects some of these issues. This is where I thought I could help. I am hoping the core developers will find my issue analysis and proposed fixes useful.

I am also trying to contribute by doing some of the simple but tedious work like updating the copyrights, eliminating warnings, etc.

Hopefully my submissions take a little bit of the load off the core IINA developers.

**Comment by low-batt** [comment]
mpv [v0.34.0](https://github.com/mpv-player/mpv/releases/tag/v0.34.0) has been released.

**Comment by low-batt** [comment]
mpv [v0.34.1](https://github.com/mpv-player/mpv/releases/tag/v0.34.1) has been released.

Contains fixes for OpenGL issues as well as others that look significant.

I have submitted PR https://github.com/iina/homebrew-mpv-iina/pull/15 to the homebrew-mpv-iina repository.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0 by the upgrade to mpv 0.34.1.
