### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by dima-xo** [iina/iina#3489]
There have been no updates since November 9, 2020. The last commit to develop was in March.

Are there more updates planned or do we need to look for alternatives?

**Comment by robertleeblairjr** [comment]
Commenting for visibility. These projects can get behind because it's work done on the side in the devs spare time. However, this one has went an unusually long periods of months without a commit to the branch from those PRs. Wondering if they are either waiting to do a full-blown onslaught of pushes, fixes, and builds on the next Xcode and macOS release. If not, then this could die off soon enough from lack of interest. Anyone tried their Telegram Group to get an update?

**Comment by robertleeblairjr** [comment]
> If you click on "Pull requests" you will see current development activity.
> 
> My understanding is that key developers are currently overloaded and having to focus on other activities. Thus the slow down in project development.

I see you've had PR for quite a while. Seems that the maintainers should have had more than just one person or coordination on this project. Otherwise, it would appear dead to many people after months of no new nightly/beta releases. But, more importantly there's not been any pushes to the development branch for months either. However, that happens often. I just would have liked to seen the devs transfer it to others who could consistently update the development instead of just letting it build up issues reporting and PRs die off without ever the fix implemented.

**Comment by low-batt** [comment]
Closing. IINA 1.3.0 has been released.

IINA 1.3.0 can be downloaded from the official [IINA](https://iina.io/) website.
