### ISSUE TITLE
Orange Dot in fullscreen mode - MacOS 12 Monteray

### ISSUE THREAD

**Issue by echohack** [iina/iina#3577]
**System and IINA version:**

- macOS 12.1 Monteray
- IINA 1.2

**Expected behavior:**

There is no orange dot (the microphone indicator) on full screen

**Actual behavior:**

The system puts an orange dot in fullscreen mode.

**Steps to reproduce:**

1. Start another application that uses the microphone, like OBS.

2. Open IINA.

3. Fullscreen.

**How often does this happen?**

Always.

<img width="1919" alt="Screen Shot 2021-12-15 at 08 20 14" src="https://user-images.githubusercontent.com/3253989/146224111-5fb459d6-c5b7-46a2-a82f-35d78f3e098a.png">

Thank you for all the work you do on this project and I hope this bug report is helpful.

**Comment by saagarjha** [comment]
My understanding is that this dot is intentionally presented over application content to prevent malicious software from trying to mess with it and surreptitiously record the user. Keeping that in mind, this is probably something we can't fix and probably do not want even if we could, because of the privacy implications.

**Comment by echohack** [comment]
Those coming to this issue might find this useful: https://github.com/s4y/undot
