### ISSUE TITLE
File Loop mode cannot be toggled off via menu command after it is turned on

### ISSUE THREAD

**Issue by vassudanagunta** [iina/iina#3626]
### System and IINA version:

- macOS 12.1
- IINA 1.2.0 build 129

### Expected behavior:

Selecting the File Loop menu item will toggle File Loop mode between `on` and `off` (with a ✔︎ appearing next to the menu item when `on`, see #3625)

### Actual behavior:

File Loop mode does not toggle off. One is forced either to restart IINA or figure out how to create a key binding to do so (very hard!).

### Workaround:

Create a key binding with the action: `cycle-values loop "no"`.  This reveals another bug: one cannot create a simple *toggle* keybinding. I have to create a separate `cycle-values loop "yes"`  A `cycle-values loop` binding does not work as expected.

**Comment by low-batt** [comment]
Reproduced for me. This is a defect. 

IINA code is treating the mpv `loop-file` property as a boolean flag. It is not a boolean. That is the source of these problems. This is the definition of the property from the mpv manual:
> **--loop-file=<N|inf|no>, --loop=<N|inf|no>**
>  &nbsp;&nbsp;&nbsp;Loop a single file N times. inf means forever, no means normal playback.

@CarterLi has a fix for this. He is currently away. I will coordinate with him when he gets back.

**Comment by vassudanagunta** [comment]
Thanks! A side note: you guys might want to consider using Issue Labels to mark issues that have been verified, was actually an mpv issue, etc. That way you could get a filtered list of the open 1.2k (‼️) issues.

**Comment by low-batt** [comment]
I'm an IINA user that noticed the core developers were overloaded and have been helping by investigating problems and posting proposed solutions. I do not have the GitHub privileges required to add labels.

The core developers are currently reviewing and merging proposed fixes as a part of preparing the next release. That may still take a while as there are a lot of fixes outstanding and we do want to be careful and not send out a release with regressions in it.

I will discuss this issue with CarterLi. He just announced he is going to be unavailable for a couple of weeks, so don't expect a quick update. This issue is simple enough that it certainly should be fixed in this coming release in my opinion.

**Comment by vassudanagunta** [comment]
Thanks for contributing to FOSS!

**Comment by low-batt** [comment]
Fix has been merged into the develop branch.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
