### ISSUE TITLE
Missing option to start iina-cli in music-mode

### ISSUE THREAD

**Issue by LangLangBart** [iina/iina#3651]
**What should IINA do:**

My problem is similar to #1852, but I want to use an iina-cli option to launch any kind of file (video or audio) in music mode.
I checked the file `MPVOption.swift` and the latest `Nightly Build` (2022-02-25 09:14:05 [ab7a3bd](https://github.com/iina/iina/commit/ab7a3bd)), but the option does not exist.

**What IINA is currently doing:**

IINA does not start in music mode :)

**Why do you think it should be added:**

(1) Ticket #1852 made a PR, but was later reverted, but it's still not possible to just launch a music URL in music mode.
(2) Videos in music mode, nice to have.

(IINA is a godsend. Good job.)

**Comment by gotham8x** [comment]
@low-batt could you please help with this?

**Comment by low-batt** [comment]
When looking for mpv options you can use it is usually easier to look in the [mpv manual](https://mpv.io/manual/stable/). The IINA wiki page [MPV Options and Properties](https://github.com/iina/iina/wiki/MPV-Options-and-Properties) also provides advice. However, since IINA replaces mpv's small controller, most mpv UI related options are ignored. In the case of music mode, that is an IINA feature, so that is why a music mode option was not found in `MPVOption.swift`.

I'm the junior newbie on the development team. In general I'm avoiding issues that request features/enhancements as I feel those need to be run past the other developers before commencing work. Also I am totally overloaded with a long list of defects I'm trying to get fixed.

However in this case `iina-cli` already has a `--pip` option to start IINA in Picture-in-Picture mode, so it feels like it should also have an option to start in music mode.

The commit in the pull request adds a new `--music-mode` option to  `iina-cli`. The help now looks like:

```text
low-batt@gag MacOS$ ./iina-cli --help
Usage: iina-cli [arguments] [files] [-- mpv_option [...]]

Arguments:
--mpv-*:
        All mpv options are supported here, except those starting with "--no-".
        Example: --mpv-volume=20 --mpv-resume-playback=no
--separate-windows | -w:
        Open all files in separate windows.
--stdin, --no-stdin:
        You may also pipe to stdin directly. Sometimes iina-cli can detect whether
        stdin has file, but sometimes not. Therefore it's recommended to always
        supply --stdin when piping to iina, and --no-stdin when you are not intend
        to use stdin.
--keep-running:
        Normally iina-cli launches IINA and quits immediately. Supply this option
        if you would like to keep it running until the main application exits.
--music-mode:
        Enter music mode after opening the media.
--pip:
        Enter Picture-in-Picture after opening the media.
--help | -h:
        Print this message.

mpv Option:
Raw mpv options without --mpv- prefix. All mpv options are supported here.
Example: --volume=20 --no-resume-playback
```

Will have to see if the changes pass review...

**Comment by LangLangBart** [comment]
Thank you for contributing a solution to my smōl feature request.

**Comment by low-batt** [comment]
IINA 1.3.2 includes the new `--music-mode` `iina-cli` option.

Many thanks to @LangLangBart and @gotham8x for pointing out the need for this option.

**Comment by low-batt** [comment]
IINA 1.3.2 contains the fix for this issue.
