### ISSUE TITLE
Pressing up key on empty welcome screen crashes IINA

### ISSUE THREAD

**Issue by Shadowknight1104** [iina/iina#3766]
**System and IINA version:**

- macOS  macOS Monterey 12.4 (M1 and Intel)
- IINA  v1.3.0 Build 130

**Expected behavior:**
Nothing happens

**Actual behavior:**
IINA crashes

<b>Crash report:</b>

[IINA-2022-05-30-175032.txt](https://github.com/iina/iina/files/8798348/IINA-2022-05-30-175032.txt)
[Pasting crash log directly exceeds word limit]

**Steps to reproduce:**
1. If you do not have an empty welcome screen, go to ```IINA > Preferences > Utilities > Clear Playback History...```
2. Go to welcome screen and press the up arrow key

**How often does this happen?**
Every time with an empty welcome screen

**Additional Info**:
This issue is possibly related to the changes made in #3739

**Comment by low-batt** [comment]
A fix has been merged into the develop branch. I reproduced the problem and confirmed the crash does not occur using the current develop branch.

**Comment by low-batt** [comment]
This problem has been fixed in IINA v1.3.0 Build **131**.

If you encounter this problem check the build number listed in the IIN/About window. If it shows build 130, then download v1.3.0 again from the [IINA](https://iina.io/) site and reinstall to update to build 131.

@Shadowknight1104 Thanks for reporting this!
