### ISSUE TITLE
JPEG-XL decoding/screenshot support?

### ISSUE THREAD

**Issue by p7r0x7** [iina/iina#3852]
**What you want IINA to do:**
Preferably, be built to enable full decoding and screenshot encoding support for JXL, as such has now been fully implemented in ffmpeg and mpv.

**What IINA does currently:**

**Why you think this should be added:**
mpv/IINA should be used as the ultimate image viewer. JXL also supports arbitrary bit depths, and thats very important for not storing 16b pngs of 10b content.

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
IINA 1.3.0 is using the latest release of mpv. IINA is not using the latest release of FFmpeg yet over reports of regressions. At this time support for JPEG XL in both mpv and FFmpeg is only available in by building using the latest sources. Before this can be supported both [mpv](https://mpv.io/) and [FFmpeg](https://ffmpeg.org/) will need to release new versions.

Supporting screenshots in [JPEG XL](https://jpeg.org/jpegxl/) format is highly desirable as the new format can properly represent screenshots from HDR movies.

Support for the new screenshot format can be seen in the mpv manual from master, [screenshot-format](https://mpv.io/manual/master/#options-screenshot-format):

>-**-screenshot-format=\<type>**
>
>    Set the image file type used for saving screenshots.
>
>    Available choices:
> 
>    **png:**&nbsp;&nbsp;&nbsp;&nbsp;PNG 
>   **jpg:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JPEG (default)
>   **jpeg:**&nbsp;&nbsp;&nbsp;JPEG (alias for jpg)
>   **webp:**&nbsp;&nbsp;WebP
>   **jxl:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JPEG XL

**Comment by p7r0x7** [comment]
FFmpeg stable 5.1 has now been released with full support for JPEG-XL.

**Comment by low-batt** [comment]
That is good to know, however the FFmpeg 5 defect that caused IINA to choose to remain on FFmpeg 4 is still open. Hopefully FFmpeg will issue a release with a fix for that defect by the time mpv issues a release with JPEG XL support.

**Comment by low-batt** [comment]
I have labeled this with the HDR feature because JPEG-XL support is needed to be able to properly support screenshots of HDR videos.

**Comment by CarterLi** [comment]
I [implemented this feature several months ago](https://github.com/iina-plus/iina/commit/8f50e64d) and finally got it working after [the recent jpeg-xl release](https://github.com/libjxl/libjxl/releases)

[test-image.jxl.zip](https://github.com/iina/iina/files/10859162/240-1000nits-0001.jxl.zip)

However, there's no known image viewer that support jxl in HDR mode, except IINA itself.

**Comment by low-batt** [comment]
Interesting timing. Just yesterday I was trying to build mpv with this support just to check and see where support is at for JPEG XL.

Using the [IINA+](https://github.com/iina-plus/iina) HDR Test release and playing the video [The World in HDR in 4K (ULTRA HD)](https://www.youtube.com/watch?v=tO01J-M3g0U) I took a screenshot in [JPEG XL](https://jpeg.org/jpegxl/) format.

I noticed is that IINA's OSD only said "Screenshot Captured". It did not display a preview image or provide buttons to show the resulting screenshot in the `Finder`. I also noticed that the OSC thumbnails for HDR videos are dim.

I found [JXLook](https://github.com/yllan/JXLook), the viewer I was using did not correctly dispay the screenshot.

IINA+ was able to properly display the resulting screenshot file.

I did find I had to enable `Pause` under `When media is opened` or `Keep window open after playback finishes` in the `General` settings otherwise IINA quickly closed the window containing the screenshot.

**Comment by p7r0x7** [comment]
Isn't JXL just supported in macOS now?

**Comment by low-batt** [comment]
Only in macOS Sonoma.

The changes in PR #4367 first attempt to decode the screenshot using [NSImage](https://developer.apple.com/documentation/appkit/nsimage). If that fails then it tries to use `FFmpeg` to decode the image. Under macOS Ventura the `NSImage` constructor returned `nil` and `FFmpeg` was used to decode JPEG-XL screenshots. My expectation is that under macOS Sonoma the `NSImage` constructor will successfully decode JPEG-XL and `FFmpeg` will not be used. I've been busy with other issues and have not had time to come back to this one and confirm that is what happens under Sonoma.

Plans are not set, but it is likely there will be one more bug fix release and then work will start on a feature release which is expected to include this enhancement.

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.
