### ISSUE TITLE
supporting HDR without iina plus

### ISSUE THREAD

**Issue by ghost** [iina/iina#3876]
**What you want IINA to do:**
I want it to support HDR videos without https://github.com/iina-plus/iina/releases/tag/v1.2.0-13 

**What IINA does currently:**
no support for hdr.

**Why you think this should be added:**
so i can watch the video in better quality...

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
The latest version of IINA, 1.3.0, contains the same HDR support that was available in IINA+ at the time 1.3.0 was released. At this point in time IINA+ contains additional changes related to HDR.

If you are having trouble with HDR in IINA 1.3.0 it could be due to the defect discussed in issue #3806, "Will M1 macbook air get iina HDR support anytime soon?". Although that sounds like some sort of problem related to that particular kind of MacBook, what it proved to be is a problem with IINA randomly failing to enable HDR for a video. So possibly you are encountering that problem. That problem has been fixed in IINA+. The fix is expected to be merged for the next release of IINA.
