### ISSUE TITLE
Audio compression is severe when playing at double speed. At double speed of the same video, NPlayer is clearer than IINA, iINA can't hear clearly

### ISSUE THREAD

**Issue by Dean12321** [iina/iina#3879]
倍速播放时音频压缩严重，同一个视频的二倍速，nplayer比iina更清晰，iina听不清
Audio compression is severe when playing at double speed. At double speed of the same video, NPlayer is clearer than IINA, iINA can't hear clearly

**Comment by low-batt** [comment]
What version of IINA are you using?

The IINA issue template contains this checkbox:
> [ ] MPV does not have this problem.

The reason for asking this question is that for video/audio playback IINA uses `libmpv` from the [mpv](https://mpv.io/) project. If the problem reproduces using the mpv player then for IINA it is an "upstream" problem. The issue must be reported to the mpv project. Once that project releases a new version with a fix, IINA must be updated to use the latest version of mpv.

For the latest release of IINA, 1.3.0, mpv was upgraded to the latest release, 0.34.1. How mpv handles audio when playback speed is higher than normal has changed since the version IINA 1.2.0 uses. When playing at 2x speed speech is significantly better with IINA 1.3.0. If you have not upgraded to 1.3.0, please do so.

If you are having problems with IINA 1.3.0, try using the mpv player. I'm sure that player will also exhibit the same issue. Please report that to the mpv project at: [mpv issues](https://github.com/mpv-player/mpv/issues)

**Comment by Dean12321** [comment]
> What version of IINA are you using?
> 
> The IINA issue template contains this checkbox:
> 
> > [ ] MPV does not have this problem.
> 
> The reason for asking this question is that for video/audio playback IINA uses `libmpv` from the [mpv](https://mpv.io/) project. If the problem reproduces using the mpv player then for IINA it is an "upstream" problem. The issue must be reported to the mpv project. Once that project releases a new version with a fix, IINA must be updated to use the latest version of mpv.
> 
> For the latest release of IINA, 1.3.0, mpv was upgraded to the latest release, 0.34.1. How mpv handles audio when playback speed is higher than normal has changed since the version IINA 1.2.0 uses. When playing at 2x speed speech is significantly better with IINA 1.3.0. If you have not upgraded to 1.3.0, please do so.
> 
> If you are having problems with IINA 1.3.0, try using the mpv player. I'm sure that player will also exhibit the same issue. Please report that to the mpv project at: [mpv issues](https://github.com/mpv-player/mpv/issues)

Thanks, 1.3.0 is much better!!! ^_^
