### ISSUE TITLE
Cannot Quit with Q-Key 

### ISSUE THREAD

**Issue by admod** [iina/iina#3881]
Hello,

The keybinding for q to Quit doesn't work on version 1.3.0. 
It was working fine on previous versions before.

I have had trying to changed the Key Bindings configuration profiles but still can't.
Also duplicated profile and manual config to q still the same result.

- macOS 
macOS 12.4 & macOS 13 beta 3

- IINA 
 1.3.0 Build 132

**Expected behavior:**
Press Q then application Quit 

**Actual behavior:**
It doesn't do anything.

**Steps to reproduce:**
Open any video
Press q  to quit -> no action
Press shift + q to quit -> application quit

- [ ] MPV does not have this problem.

**How often does this happen?**
Everytime

**Comment by low-batt** [comment]
Initially I was not able to reproduce the issue using the `IINA Default` key bindings. I had time today to take another look and found a regression when using the `mpv Default` bindings. Are you using the mpv key bindings?

There are a number of issues with IINA key bindings. Work has started on fixes. That work started when we were trying to halt merging and release 1.3.0. Many of the key binding related fixes did not make it into 1.3.0. These fixes are considered important. We will be getting back to merging the outstanding key binding fixes.

I'm not that familiar with this area of IINA. Hopefully @svobs will chime in.

### Analysis

In IINA 1.2.0 the `mpv Default` key bindings were missing some bindings that mpv had added over time. This was reported in issue #3718. That issue was fixed for 1.3.0 by the PR #3727.

For "q" IINA's mpv bindings now contains:
```text
q quit
Q quit-watch-later                     # exit and remember the playback position
q {encode} quit 4
```

I believe the issue is the addition of the binding to `{encode} quit 4`. If I duplicate the `mpv Default` key bindings and in the new custom key bindings delete the `q` to `{encode} quit 4` binding the "q" key works as before.

So what is this binding doing? From [Command Interface quit](https://mpv.io/manual/stable/#command-interface-quit-[%3Ccode%3E]):
>**quit [\<code>]**
> &nbsp;&nbsp;&nbsp;&nbsp;Exit the player. If an argument is given, it's used as process exit code.

So the `quit 4` makes mpv exit with a return code of 4. From [EXIT CODES](https://mpv.io/manual/stable/#exit-codes):

>Normally mpv returns 0 as exit code after finishing playback successfully. If errors >happen, the following exit codes can be returned:
>
> &nbsp;&nbsp;&nbsp;&nbsp;1:	Error initializing mpv. This is also returned if unknown options are passed to mpv.
> &nbsp;&nbsp;&nbsp;&nbsp;2:	The file passed to mpv couldn't be played. This is somewhat fuzzy: currently, playback of a file is considered to be successful if initialization was mostly successful, even if playback fails immediately after initialization.
> &nbsp;&nbsp;&nbsp;&nbsp;3:	There were some files that could be played, and some files which couldn't (using the definition of success from above).
>  &nbsp;&nbsp;&nbsp;&nbsp;4:	Quit due to a signal, Ctrl+c in a VO window (by default), or from the default quit key bindings in encoding mode.
>  
> Note that quitting the player manually will always lead to exit code 0, overriding the exit code that would be returned normally. Also, the quit input command can take an exit code: in this case, that exit code is returned.

What does the `{encode}` command prefix do? From [Input Sections](https://mpv.io/manual/stable/#input-sections):
> Input sections group a set of bindings, and enable or disable them at once. In input.conf, each key binding is assigned to an input section, rather than actually having explicit text sections.
>
> See also: enable-section and disable-section commands.
>
> Predefined bindings:
>
> **default**
>  &nbsp;&nbsp;&nbsp;&nbsp;Bindings without input section are implicitly assigned to this section.
>  &nbsp;&nbsp;&nbsp;&nbsp;It is enabled by default during normal playback.
> **encode**
> &nbsp;&nbsp;&nbsp;&nbsp;Section which is active in encoding mode.
> &nbsp;&nbsp;&nbsp;&nbsp;It is enabled exclusively, so that bindings in the default sections are ignored.

From [enable-section](https://mpv.io/manual/stable/#command-interface-enable-section):
> **enable-section \<name> [\<flags>]**
>
>  This command is deprecated, except for mpv-internal uses.
>  ...

Seems mpv is moving away from input sections although I'm unsure as to what mpv is doing with them internally.

I found the following uses of input sections:

```bash
low-batt@gag config (develop *$=)$ grep -i encode input.conf 
q {encode} quit 4
ESC {encode} quit 4
CLOSE_WIN {encode} quit 4
```
I'm thinking the correct fix for IINA is to remove these 3 bindings.

**Comment by svobs** [comment]
@low-batt nice detective work. This looks like a bug caused by an obscure feature of mpv.

Input sections are indeed used by mpv internally, and the code around them is pretty messy in places. Unfortunately, a basic understanding of how they work is needed when using Lua scripts, because they can set bindings dynamically, and when using multiple scripts simultaneously their bindings can interfere with each other. I fear the same issue may come up with bindings set via IINA plugins, and would like to build up to that discussion...

An input section is a just a list of input bindings, and mpv puts these in a stack to determine which have priority. If I go into IINA's Advanced settings and set the mpv option `msg-level` to `input=trace` and then restart IINA & play a video, I see this in my log:
```
[   0.235][t][input] active section stack:
[   0.235][t][input]  default 12
[   0.235][t][input]  input_stats 12
[   0.235][t][input]  input_forced_stats 12
[   0.235][t][input]  showhide 12
[   0.235][t][input]  showhide_wc 12
[   0.235][t][input]  input_console 12
[   0.235][t][input]  input_forced_console 12
[   0.235][t][input]  input_webm 12
[   0.235][t][input]  input_forced_webm 12
[   0.235][t][input]  input_osc 12
[   0.235][t][input]  input_forced_osc 12
```
This lists the stack of active input sections, from bottom to top (with `default` being at the bottom). The sections which start with `input_` are generated for Lua scripts and end with the script name. (I've got the webm script installed, but the others are all built-in.) Each section can contain key bindings, and each binding can be either "default" (i.e., "weak") or "force" (i.e, "strong"). There are 2 separate sections for each Lua script because mpv appears to group the script bindings according to whether they are "force" or not, but each section can contain a mix of force or default bindings (including the confusingly named "default" section, which simply refers to the unnamed section which contains the contents from input.conf).

When a user types a key, mpv starts at the top of the stack and goes down. The topmost "force" binding will be used if one is found; otherwise, it will use the topmost "weak" binding. Therefore, a "weak" binding from high in the stack will override a "weak" binding with the same key from lower in the stack, and a higher-level "force" will override a lower-level "force", but a "weak" binding will never override a "force" binding.

"Weak" bindings can be specified in mpv's input config file by adding the line: `default-bindings start`, and all lines below it will be treated as weak. IINA doesn't support this currently and I'm not sure it needs to, although the way it currently stumbles over parsing that line could be improved.
---

So I did some testing, and it looks like mpv loads Lua scripts before it loads the input.conf file, and the `{section_name}` modifier allows the user to add bindings to sections which have already been created. If the section does not exist, the command is ignored. I'm not really sure if this is actually useful though. I suppose in theory it could be used to add a additional key binding to a script when it is loaded, but I think your intuition is probably correct that this is just a vestigial feature.

Besides changing the input config, I can add a patch so that IINA will simply ignore all key bindings that contain a `{section_name}` identifier - except if it's `{default}`, in which case the section identifier should just be removed because the input config is already specifying the default section and it's redundant. I might need to roll this into an existing PR (probably #3833) because there's just no way to avoid a code conflict at this point.

**Comment by low-batt** [comment]
Given the internal use by mpv it doesn't look like input sections will be going away. I agree IINA should be ble to parse conf files containing input sections and ignore definitions that aren't in the default section.

We do need to finish the review of the plugin system and get back to merging the outstanding PRs to avoid a buildup of merge conflicts,.
