### ISSUE TITLE
Some .ass subtitle can not be played.

### ISSUE THREAD

**Issue by kirbyzhou** [iina/iina#3889]
macOS 12.5
IINA 1.3.0 Build 132
Intel Mac

[Stranger.S01E01.WEBRip.x264-ION10.chi.ass.zip](https://github.com/iina/iina/files/9175958/Stranger.S01E01.WEBRip.x264-ION10.chi.ass.zip)
![image](https://user-images.githubusercontent.com/3401630/180650961-892ce912-b150-4417-bb7a-5ed8b34b08b6.jpeg)

**Comment by hooke007** [comment]
A valid ASS subtitle should be started with `[Script Info]`

![Snipaste_2022-07-24_20-15-32](https://user-images.githubusercontent.com/41094733/180662446-8ede773a-4e6e-4d40-90de-1326f5c6b2d3.jpg)


Your invalid subtitle:

![Snipaste_2022-07-24_20-16-22](https://user-images.githubusercontent.com/41094733/180662467-bb80d386-1b20-4ea2-8cb5-c9b55fa3a835.jpg)

**Comment by low-batt** [comment]
As @hooke007 correctly indicated the `Unsupported external subtitle` error reported by IINA is expected. The attached `.ass` file is invalid.

For subtitles in [Advanced SubStation Alpha](https://en.wikipedia.org/wiki/SubStation_Alpha) format, IINA (through [mpv](https://mpv.io/)) uses the [libass](https://github.com/libass/libass) library to process the subtitle file. From the ASS specification referenced on the libass GitHub page:

> **2. The sections in a Sub Station Alpha script**
>
> **\[Script Info]**
> This section contains headers and general information about the script.
> The line that says “\[Script Info]” **must** be the first line in a v4 script.

The specification could not be clearer, if the file does not start with `[Script Info]` it is not a valid `.ass` subtitle file. That line is not optional, it **must** be present.

The other odd thing about this subtitle file is that the title was left set to a "placeholder":
```text
Title: Default Aegisub file
```

If you open the `.ass` file in TextEdit and add a new line with the text `[Script Info]` to the front of the file, IINA will accept the subtitle file.

I am going to close this issue as invalid, due to the `.ass` file missing the required header.
