### ISSUE TITLE
Download stream

### ISSUE THREAD

**Issue by kyellareddy** [iina/iina#3914]
I think it should be possible to download a stream when viewed in IINA.
For example, when someone uses the browser extension to open an online video in IINA, there should be a way for them to download it straight from there.

**Comment by mcstrassell09** [comment]
You can record a live stream using  MPV's --stream-record option. It requires a little workaround to get to work.  Here are the steps:

- First you need to use terminal and CD to a directory you want the recording to be created. Then open IINA using the command line. (This makes IINA use the working directory you are in instead of "/" which is not writable).

-Create two custom key bindings like this: 

R      set stream-record "${media-title).ts"; show-text ${media-title} 
r       set stream-record ""; show-text "Closing ${media-title}.ts"

<img width="643" alt="IINA-screen-record" src="https://user-images.githubusercontent.com/47344882/188530871-28cbb97f-f3db-4d75-a1ab-985a63d2cafb.png">

The first will start a stream recording with the name of the currently playing file with extension ".ts"
The second will stop the screen recording 

I haven't been able to transcode directly to .mp4 successfully but it's probably possible using deep-dive into the source code. So eventhough the .ts file will play fine with IINA, I will transcode it later to my desired format with FFMPEG.

If you are playing a playlist and skip to the next file before stopping the stream-recording, the recording will be overwritten with the next media. So to fix this, modify a key-binding to stop the stream recording automatically when going back/forward  in playlist. Use this just incase you forget to stop the recording before switching to next media


<img width="643" alt="IINA-screen-record2" src="https://user-images.githubusercontent.com/47344882/188532063-8faf7ef5-27c5-4ef1-893f-55ae2d4330f0.png">

If you don't know if you are currently recording or if IINA is in the correct working directory add these watch properties to the  IINA inspector window. 

<img width="864" alt="Screenshot 2022-09-05 at 10 11 50 PM" src="https://user-images.githubusercontent.com/47344882/188532454-bd87bb94-ae6c-49ea-8bb8-22c6ecae4f9d.png">
