### ISSUE TITLE
IINA Crashes on macOS 13.0

### ISSUE THREAD

**Issue by ddddavid-he** [iina/iina#3931]
IINA crashes and gets a frozen interface when playing media on macOS 13.0 Public Beta.

**System and IINA version:**

- macOS 13.0
- IINA 1.3.0 Build 132

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

No crash report found.

</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by low-batt** [comment]
@ddddavid-he Thanks for reporting this.
@selsta Thanks for posting a link to the mpv issue.

The mpv issue title:
> mpv freezes on macOS Ventura beta 13.0 Beta 5 (22A5331f) after update #10579

Contains a typo. The problem appears after updating to [macOS 13 beta 6 (22A5331f)](https://developer.apple.com/news/releases/?id=08252022a)

I have labeled this issue as upstream because mpv has this problem as well.

Although that mpv issue is closed due to the problem being reported against a Beta version of macOS, investigation into the issue appears to be in progress. 

@Akemi in the review of the proposed change to mpv in PR https://github.com/mpv-player/mpv/pull/10585 has indicated the mpv behavior in question is related to a workaround  for OpenGLrendering.

@Coeur has opened a [Feedback Assistant](https://support.apple.com/guide/feedback-assistant/welcome/mac) case with Apple.

IINA will have to keep a close eye on mpv issue https://github.com/mpv-player/mpv/issues/10579 and PR https://github.com/mpv-player/mpv/pull/10585.

**Comment by low-batt** [comment]
Would someone experiencing this failure please use [Activity Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac) to collect a process sample and post it here.

To do this run IINA and when the problem reproduces open `Activity Monitor` in `/Applications/Utilities`. Find IINA in the list of processes displayed by the monitor and click on it to select that process. The monitor will highlight it in blue. In the `Activity Monitor` select `Sample Process` under the `View` menu. A panel will pop up and the monitor will sample the process for a few seconds. Save the results to a file. Drag and drop that file to this issue in the browser.

**Comment by mcstrassell09** [comment]
[Sample of IINA-freeze.txt](https://github.com/iina/iina/files/9481167/Sample.of.IINA-freeze.txt)

I have been getting the same issues with IINA and MPV freezing. Here's the sample process you requested. 

macOS 13.0  beta 6 (22A5331f)
IINA 1.3.0 Build 132
mpv 0.34.1

**Comment by low-batt** [comment]
I see @ddddavid-he has closed this issue without giving a reason as to why.

My guess would be that it is because mpv PR https://github.com/mpv-player/mpv/pull/10585 has been closed by @Ceour with this comment:
> Seems "Apple will revert the change causing the hang"

Apparently Apple responded to the feedback @Ceour submitted.

I would have left this issue open until Apple released a Ventura update with a fix so others running into this with the current Ventura Beta could find it.

@mcstrassell09 Thanks for posting the process sample.

Although we were pretty sure the IINA freeze was the same problem mpv was experiencing, it is always good to double check. The sample of IINA you took shows the main thread blocked in `delete_buffer`:

```text
    +                                     2388 delete_buffer(unsigned long, CAImageQueueBuffer*, void*)  (in QuartzCore) + 317  [0x7ff81647f243]
    +                                       2388 CAImageQueueCommit::~CAImageQueueCommit()  (in QuartzCore) + 20  [0x7ff816246cb4]
    +                                         2388 CA::Context::Generic::increment_commit_seed()  (in QuartzCore) + 26  [0x7ff8163aa25a]
    +                                           2388 _pthread_mutex_firstfit_lock_slow  (in libsystem_pthread.dylib) + 212  [0x7ff80e71f9c8]
    +                                             2388 _pthread_mutex_firstfit_lock_wait  (in libsystem_pthread.dylib) + 76  [0x7ff80e721ba3]
    +                                               2388 __psynch_mutexwait  (in libsystem_kernel.dylib) + 10  [0x7ff80e6e796a]
```

This is consistent with the mpv process sample posted in the mpv issue:
```text
    +                                     2014 delete_buffer(unsigned long, CAImageQueueBuffer*, void*)  (in QuartzCore) + 317  [0x7ff817279243]
    +                                       2014 CAImageQueueCommit::~CAImageQueueCommit()  (in QuartzCore) + 20  [0x7ff817040cb4]
    +                                         2014 CA::Context::Generic::increment_commit_seed()  (in QuartzCore) + 26  [0x7ff8171a425a]
    +                                           2014 _pthread_mutex_firstfit_lock_slow  (in libsystem_pthread.dylib) + 212  [0x7ff80effd9c8]
    +                                             2014 _pthread_mutex_firstfit_lock_wait  (in libsystem_pthread.dylib) + 76  [0x7ff80efffba3]
    +                                               2014 __psynch_mutexwait  (in libsystem_kernel.dylib) + 10  [0x7ff80efc596a]
```

Seems we are waiting for Apple to fix the regression, hopefully in the next release of Ventura.

**Comment by mcstrassell09** [comment]
[Spindump.txt](https://github.com/iina/iina/files/9484146/Spindump.txt)

I know very little about debugging a kernel but can see the main thread is blocked by the turnstyle mechanism.  I hope Apple comes through and fixes this. Thanks for the info.

**Comment by mcstrassell09** [comment]
[Spindump.txt](https://github.com/iina/iina/files/9484179/Spindump.txt)

I know next to nothing about kernel debugging but can see the main thread is blocked by the turnstyle process. Hopefully Apple comes through and makes it right.  


<img width="867" alt="shot" src="https://user-images.githubusercontent.com/47344882/188301479-f53a800a-564f-4ff1-867b-c1db9712a6e9.png">

**Comment by MrCrispyBacon** [comment]
**IINA 1.3.0 Build 132 and mpv 0.34.1 have the same issue on macOS Ventura 13.0 beta 7 (22A5342f)** 

Problem not solved yet....guess updates for both apps will be an option as  continuously lagging and freezing tons....That's a bugger!!!
