### ISSUE TITLE
IINA freezes the entire system when entering and exiting from full screen mode on macOS 13.0 Ventura Beta 8 (22A5352e)

### ISSUE THREAD

**Issue by ddddavid-he** [iina/iina#3953]
**System and IINA version:**

- macOS 13.0 Beta 8 (22A5352e)
- IINA 1.3.0 Build 132

**Expected behavior:**

**Actual behavior:**

As what the title writes. I was watch a video full screen, it was unable to start any other applications from launch panel or dock. (this doesn't happen every time)

When I then exited from the full screen mode or quit IINA with the video is still playing, everything freezes except for applications started before IINA. The IINA.app seems to run into some problems in terminate the program as the IINA remain in the state bar after exiting the application. (as it is in the screenshot)

<img width="1440" alt="截屏2022-09-25 16 34 39" src="https://user-images.githubusercontent.com/58453183/192135045-89accda6-45e0-4a50-9e85-bcdfbc978b8d.png">

The only solution to recover is to press the power button to force restart.
<details>
<summary><b>Crash report:</b></summary>

nothing related to IINA found in log files

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

upload later
```
```
</details>

<br>

**Steps to reproduce:**
- open a video file
- switch to full screen mode
- **do not stop the video** and exit from full screen mode (or quit IINA)
- if everything's alright, try the above again

- [ ] MPV does not have this problem.

**How often does this happen?**
everytime

**Comment by ddddavid-he** [comment]
checkout the log files here

[mpv.log](https://github.com/iina/iina/files/9640325/mpv.log)

[iina.log](https://github.com/iina/iina/files/9640324/iina.log)

**Comment by MrCrispyBacon** [comment]
https://github.com/mpv-player/mpv/issues/10579#issuecomment-1257137416

mpv and IINA same result....freezing macOS system...and Ventura final version will be released in October and nothing changed...for more that we can complain about it, the issue is still here and absolutely nothing is being done...and at the moment is worst than ever!

Start updating the apps because Apple won't fix it!!!

Meanwhile Im downloading VLC coz way too much inconvenience

**Comment by ddddavid-he** [comment]
Truly inconvenient.
But I really love the user interface of IINA

**Comment by low-batt** [comment]
@MrCrispyBacon I noticed your post to the mpv issue and was alarmed.

I see there are now more replies to the mpv issue since I last checked including @ddddavid-he confirming the problem exists in Beta 8.

This is the last lines of the IINA log:
```swift
16:31:03.050 [iina][d] App should terminate
16:31:03.050 [player0][d] Write watch later config
16:31:03.072 [iina][d] App will terminate
```

The "App should terminate" indicates IINA was notified by Apple's AppKit that it should terminate. This is the point at which the application should save any data. You can see from the next log message IINA is using mpv's watch later feature to save the state of playback. The last line "App will terminate" indicates IINA was notified by AppKit that the application is terminating. In response to that IINA closes the log file. This process is referred to as "Graceful Application Termination".

That the freeze is occurring at this point and that it makes macOS unresponsive is not quite matching up with the behavior seen with the problem that started with Beta 6 and continued with Beta 7. That this is also happening when exiting full screen mode also does not line up with the previous problem. This is suggestive of Apple having fixed the original regression and either this is a new unrelated problem or a new problem related to how they fixed the previous problem.

But that is just speculation. Need more evidence to say for sure. For a freeze we need to see an Activity Monitor process sample taken at the time the application is frozen. Can't create a sample if macOS is not responding.

When the Mac was not responding did you try bringing up [Mission Control](https://support.apple.com/en-us/HT204100) and switching to another application?

It used to be that software developers resisted making significant changes near the end of a beta test cycle. But with the current development methodologies developers are more willing to put in risky changes shortly before a release.

This definitely needs to be reported to Apple. Yes, again. Please use the [Feedback Assistant](https://support.apple.com/guide/feedback-assistant/intro-to-feedback-assistant-fba2e39e53f5/mac) and let Apple know the behavior is worse in Beta 8.

**Comment by ddddavid-he** [comment]
<img width="1440" alt="截屏2022-09-25 22 15 15" src="https://user-images.githubusercontent.com/58453183/192148447-57ac7ab0-fca5-41ba-b3d8-ffd5d459f77c.png">

It's possible to bring up Mission Control and switch to existing applications. The `htop` seems like this. 

The system re-logins and recovers after I killed the process named `_windowser`
<img width="1440" alt="截屏2022-09-25 22 16 21" src="https://user-images.githubusercontent.com/58453183/192148532-06feb95b-2106-4248-88a0-1c5d7f1c74d4.png">

**Comment by low-batt** [comment]
The Window Server is a component of macOS. There are problems in this area of macOS as discussed in [Monterey crashes with WindowServer error after going full screen with YouTube](https://discussions.apple.com/thread/253316950). 

The problem being reported in that Apple discussion is this kernel panic:
```text
panic(cpu 2 caller 0xffffff8013d6799f): userspace watchdog timeout: no successful checkins from WindowServer in 120 seconds
```

That crash was triggered by the macOS daemon `watchdogd`. That daemon is a [Watchdog timer](https://en.wikipedia.org/wiki/Watchdog_timer). If a macOS service freezes and fails to report in to the watchdog, eventually the watchdog will trigger a macOS panic to force a reboot. In the version of macOS that crashed that timeout was set to 120 seconds for `WindowServer`.

In the failure at hand it appears that the macOS `WindowServer` daemon is frozen. Not clear why this did not trigger a panic. Possibly the timeout has been increased in Ventura and you would have to let the Mac sit for longer before a crash is triggered.

What this tells me is that there are problems in this area of macOS and that means Apple may be attempting to make fixes in Ventura. Could be a "fix" made the problem worse.

This definitely needs to be reported to Apple.

**Comment by ddddavid-he** [comment]
I’ve submitted a report in Feedback Assistant. Thanks for your kind attention.

**Comment by singhalrishi27** [comment]
This is more of macOS issue than IINA's report it in Feedback Assistant

**Comment by ddddavid-he** [comment]
> This is more of macOS issue than IINA's report it in Feedback Assistant

I've made a report already.

**Comment by low-batt** [comment]
@ddddavid-he Thanks so much for reporting this to Apple. Hopefully enough people report this that Apple will notice and provide a proper fix. Getting awfully late in the Ventura Beta cycle to have these kinds of problems. Hopefully Ventura won't be another macOS .0 release that users judge as too buggy to use.

Always fine to enter an IINA issue even if the root cause of the problem is not in IINA's codebase. As IINA is layered on top of many other open source projects this is the case for many problems. Such problems are referred to as an "upstream" issue.

**Comment by singhalrishi27** [comment]
Hi can you just send me screenshot of the report you send to apple

**Comment by ddddavid-he** [comment]
@singhalrishi27
I am glad to. But I’ve done it in Chinese.

![43AEA281-95F1-4F83-8D16-CBCECAFAAFA1](https://user-images.githubusercontent.com/58453183/192375472-3d2fc44f-f024-4f37-8789-84f88c3b52a5.jpeg)

**Comment by ddddavid-he** [comment]
The same problem occurs when playing html5 based web videos on iOS Safari. Thus, it is Apple to be blamed instead of IINA. 

Thank you all for your attention.

**Comment by low-batt** [comment]
@ddddavid-he Thanks for continuing to report your findings.

I'm reading reports that the Ventura Beta 9 release still has this problem.

**Comment by ddddavid-he** [comment]
That’s disappointing

**Comment by iancbogue** [comment]
I seriously regret installing the Ventura beta. Between this bug and not being able to use any search bar system-wide, it's been a nightmare. But I've done too much since I installed to make downgrading to Monterey a viable option. I also reported this in Feedback Assistant but they don't seem to be connecting other reports together for anything.

**Comment by Kossio** [comment]
I'm also getting this but wanted to add that it's a weird system freeze? Seems like everything is still running just fine, some windows keep updating, your cursor is still responsive, but nothing is interactable. Even IINA keeps playing the video until the video ends. You can also exit to the user log in screen, but logging in back has no effect.

**Comment by ddddavid-he** [comment]
> I'm also getting this but wanted to add that it's a weird system freeze? Seems like everything is still running just fine, some windows keep updating, your cursor is still responsive, but nothing is interactable. Even IINA keeps playing the video until the video ends. You can also exit to the user log in screen, but logging in back has no effect.

yes it is not totally freezing but unable to interact

**Comment by low-batt** [comment]
A weird system freeze is a good description. See the post from @ddddavid-he above that contain the screen shots. That post reports killing the Window Server process recovers the system.

The Window Server is a component of macOS. When that component locks up you get this kind of behavior where things sort of work, but some operations are broken. This is because lower levels of macOS are still working fine.

**Comment by Coeur** [comment]
macOS Ventura Beta 10 is now available and might be resolving the fullscreen issue.

**Comment by ddddavid-he** [comment]
The problem seems to be solved in developer beta 10 and public beta 8. 🎉

**Comment by LeOndaz** [comment]
I still experience this on M1 Pro ventura 13.0

**Comment by low-batt** [comment]
Hi @LeOndaz,

This particular issue was an Apple defect added to macOS during the Ventura Beta releases and fixed before the official public release. Therefore it is surprising that you are experiencing it under macOS 13.0.

If the entire system is freezing then whatever you are experiencing it is a macOS defect. The latest macOS Ventura release is 13.2. I definitely suggest upgrading to that version over 13.0.

Unfortunately even the latest version of Ventura still contains regressions compared to Monterey.
