### ISSUE TITLE
[Ventura] Non-IINA monitor momentarily blackened while using Firefox or Chromium in full screen while IINA is also full screen

### ISSUE THREAD

**Issue by dbenjaminmiller** [iina/iina#4015]
**System and IINA version:**

- macOS 13.0
- IINA - Both 1.3.0 (132) and nightly@f8811b6

**Expected behavior:** When Firefox/Chromium is open on monitor in full screen, and IINA is in full screen on the other, there should be no momentarily blackening of any screens at any time.

**Actual behavior:** When I open Firefox full-screen on one monitor, and IINA full-screen on the other, the screen with Firefox will sometimes be blackened. Sometimes this occurs somewhat randomly when a key is pressed on the keyboard while I have the Firefox window open. But the most consistent way to get this to occur is by clicking in the Firefox screen and then moving the cursor to the IINA monitor, which usually (though not 100% of the time) causes the Firefox monitor to go black, until I either click on the IINA monitor or move my mouse back (usually), though the screen will un-black after a moment in many cases. The screen also sometimes will turn black when I make a keystroke in the Firefox screen without moving my cursor to the IINA screen. This often happens when I am typing in a text box on a webpage, especially when I press the space bar.

I have tried this using both Firefox 106.0.2 (current stable) and Firefox's latest nightly build as of the time of my writing this, with the same results. I also tried using Chromium 106, which seems susceptible to the same problem. With most other programs, this does not occur (e.g., with Safari and Apple Mail). I don't know why it occurs with Firefox and Chromium and not those other programs, but it clearly has something to do with IINA, because it occurs with multiple other programs on the other screen, and it does not happen with MPV, nor with any other video player I try (e.g., QuickTime and VLC).

This phenomenon only occurs when a video is playing, not when one is open but paused. This does occur even if the video and/or audio tracks are disabled. More than that, whenever there is a UI panel of some kind open in IINA (playlist, settings sidebar, about window, etc.) above the IINA full-screen window, in any way, then the phenomenon does not occur even while playback is actually active.

The phenomenon does not occur when there are two windows split-screen on the same screen. This includes when IINA and Firefox are split on halves of the same screen, or even in fact when IINA is on one window and two firefox windows are split-screen in full-screen mode on the other.

The issue occurs no matter what hardware acceleration settings are chosen in Firefox or IINA. It also occurs no matter what codec is used in the video played in IINA and no matter its framerate (including whether it has an integer or non-integer framerate).

Both the monitors are external non-HiDPI FHD screens attached to a headless Mac Studio, one via HDMI and the other via Thunderbolt/DisplayPort cable.

Also, none of this ever occurs when one application or the other is NOT full-screen. This occurs whether IINA is set to legacy or new full screen mode.

**Steps to reproduce:** See above.

- [X] MPV does not have this problem.
This does not occur with MPV, nor with any other player I have used (QuickTime, VLC).

**How often does this happen?**
Almost every time the described steps are taken, although it is slightly random, it seems, and definitely doesn't happen quite 100% of the time.

**Comment by low-batt** [comment]
First let me say how helpful the detailed report was. I may not have been able to reproduce this problem if it were not for the detailed information provided.

I am using a 16" MacBook Pro with the M1 chip and a 27" Apple/LG Ultrafine monitor. I ran Firefox 106.0.2 in full screen on the external monitor and IINA 1.3.0 in full screen on the built-in display playing a non-HDR video. Clicking on Firefox in the external monitor and then moving the cursor to the video playing on the internal display would sometimes cause the external monitor to go black.

IINA has a feature for blacking out other monitors while in full screen. I confirmed the code for that feature is not being called.

I tried reproducing the problem using mpv instead of IINA and was unable to reproduce the behavior using mpv.

This aspect of the behavior is very interesting:
> This phenomenon only occurs when a video is playing, not when one is open but paused. This does occur even if the video and/or audio tracks are disabled. More than that, whenever there is a UI panel of some kind open in IINA (playlist, settings sidebar, about window, etc.) above the IINA full-screen window, in any way, then the phenomenon does not occur even while playback is actually active.

That behavior matches another problem. You may have noticed all the issues reporting the screen dimming while playing a HDR video in full screen. That problem also exhibits this same behavior.  The screen does not dim if playback is paused. The screen does not dim when the OSC is displayed.

A workaround is in development for that problem. Running a version of IINA with that workaround I was unable to reproduce the blacking out of the screen running Firefox. Looks like that workaround needs to be applied for more than HDR videos.

The workaround makes some UI elements very transparent instead of totally hidden. This means IINA is always displaying a UI element, thus working around the problem.

So what is the root cause of these problems? We don't know. It is beginning to look like Apple has broken macOS in a very strange way.

**Comment by dbenjaminmiller** [comment]
I am now able to reproduce this with two Firefox windows with Netflix in one. So this is definitely a MacOS bug. Nevertheless, the workaround would be appreciated.

**Comment by low-batt** [comment]
I really appreciate you reporting that. When you update some software and things start malfunctioning most of the time it is the fault of the updated software. But some of the time the updated software is completely correct and just happens to trigger existing problems that were lurking in other software. I was starting to get worried that IINA was doing something wrong.

The idea behind the workaround being tested is to make the OSC extremely transparent instead of completely hiding it, taking advantage of the fact that the problem does not occur when IINA is showing other UI components. At the moment we are trying to figure out why the workaround is not working for a user that tested it.

**Comment by dbenjaminmiller** [comment]
It seems the underlying issue is no longer present in MacOS 12.3, from my testing.

**Comment by low-batt** [comment]
Thanks for the report. I assume "12.3" is a typo and was supposed to refer to macOS 13.2.

I just upgraded to macOS 13.2. The problem with dimmed HDR content in full screen that we thought was related to this problem is still present.

**Comment by dbenjaminmiller** [comment]
Yeah, that's what I meant, 13.2. 

Interesting that one would (apparently) be fixed and not the other. Don't know enough to say what might be the adjustment that was made.
