### ISSUE TITLE
Black window when switching between video mode and music mode w/ video paused

### ISSUE THREAD

**Issue by uiryuu** [iina/iina#4055]
**System and IINA version:**

- macOS 13
- IINA 1.3.1

**Expected behavior:**
After entering video mode or music mode, the window should display paused video frame or audio artwork.

**Actual behavior:**
When paused/0 fps (audio artwork), black screen is displayed.

**Steps to reproduce:**
- Open a video
- Pause it
- Enter Music mode manually

- [x] MPV does not have this problem.

**How often does this happen?**
Always

This is a regression of https://github.com/iina/iina/issues/2057

**Comment by edrozenberg** [comment]
Same issue while playing an mp3 audio file (not paused). Art display shows as black, time indicator does not change, until I drag the position slider left or right a little.

**Comment by low-batt** [comment]
Reproduced for me. Investigating…

**Comment by low-batt** [comment]
The fix in commit https://github.com/iina/iina/commit/f8811b6b696640a1ff0511f6c328294b13fa7599 introduced this regression. This was supposed to standardize drawing to always use the `com.colliderli.iina.mpvgl` dispatch queue in order to correct data races. However `CAOpenGLLayer` is sometimes queuing drawing to the main thread. That means the data races are not fixed. TSan did not detect this. The queuing by  `CAOpenGLLayer` instead of drawing breaks forced drawing as `forceRender` is set and reset in `VideoLayer.draw(forced)` around the call to `display`. When that is queued to the main thread instead of being executed inline, `forceRender` has usually been reset to `false` by the time `canDraw` is called and drawing does not happen. In the issue at hand forced drawing is required and is not happening due to this change.

With `CAOpenGLLayer` queuing some work to the main thread it is not possible to solve the data races over the `VideoLayer` properties by standardizing access to one dispatch queue.

I will create a PR that backs out the problematic changes in the above commit and instead adds locking to correct the `VideoLayer` data races.

**Comment by low-batt** [comment]
IINA 1.3.2 contains the fix for this issue.
