### ISSUE TITLE
The Find Subtitle Result Window was too Narrow to see the whole name.

### ISSUE THREAD

**Issue by owenzhao** [iina/iina#4057]
**What you want IINA to do:**

The result window of find subtitle should be much much more wider.

**What IINA does currently:**

Too narrow to see the full name, we need to see the full name to get the subtitle that is mostly match my video.

**Why you think this should be added:**

**Examples of other projects that have something similar:**

**Comment by Iiii-I-I-I** [comment]
To complete the **Why you think this should be added:** field, here are some situations where I've needed to read the full filename:

- to see the year of release, because there are multiple remakes with the same title
- to see the format of the movie (streaming, Blu-ray, restoration, etc.), because the timings may be off
- to see the type of subtitle (forced, CC, etc.), because I'm not hearing impaired and do not need SDH subtitles

This type of information is usually listed at the end, where it gets cut off by IINA's search window. Making sure I'm downloading the correct file is even more important for OpenSubtitles now that they've added a daily limit.

**Comment by Iiii-I-I-I** [comment]
Some possible solutions:

* show the full text when hovering over the title, the same way title text appears when hovering over an `<a>` tag on the web. Could be less work than messing with the UI?
* add more information to the metadata row (I don't know if the OpenSubtitles API gives you that kind of detail). Here is a mockup, with the current on the left and proposed on the right:

![iina](https://github.com/iina/iina/assets/647835/c5ae3581-8f7b-4336-8be0-03244816fd7b)

**Comment by svobs** [comment]
> show the full text when hovering over the title, the same way title text appears when hovering over an <a> tag on the web. Could be less work than messing with the UI?

This is trivial (a checkbox in the UI). I may post a PR for it.

However, you can try another workaround, which exists because the table width is set by the width of its title. Try increasing the OSD text size in IINA's Settings:
<img width="718" alt="SCR-20240216-unyk" src="https://github.com/iina/iina/assets/2213815/e161fc99-971f-4a28-a4a9-1e14abf492a6">

**Comment by Iiii-I-I-I** [comment]
Thanks all for addressing this so quickly! I look forward to the title text + new plug-ins in a future update.

**Comment by low-batt** [comment]
This was changed for IINA 1.3.5.
