### ISSUE TITLE
Iina loses focus sometimes when taking a screenshot

### ISSUE THREAD

**Issue by beyondcompute** [iina/iina#4233]
**System and IINA version:**

- macOS 13.2
- IINA 1.3.1 Build 133

**Expected behavior:**
When I take a screenshot (IINA is full-screen on one display) the focus should stay on the playing window. The option “show previews after taking screenshots“ is **not** set.

**Actual behavior:**
Sometimes (not sure how to reproduce reliably, but in about 10% of the cases) the window that is playing loses focus. The MacOS menu bar still says “IINA” and I have no others IINA windows open. I lose the ability to control the playback. So I have to click on the window to regain control over playback.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
Maybe in 10-15% of the cases. Not systematically though.

**Comment by low-batt** [comment]
Sorry for the slow response. Lots going on.

Do you have the IINA setting `Use legacy full screen` enabled? This feature was severely damaged by incompatible changes made by Apple in macOS Big Sur and still has not fully recovered.

I tried IINA with that setting disabled and enabled and did not encounter the problem. It could either be because of differences in how I tested, or as it is only failing for you 10-15% of the time it could be I was lucky. Here is how I tested…

I configured these settings in IINA:
- Enabled `Black out other monitors while in full screen`
- Disabled `Show previews after taking screenshots`

I attached my MacBookPro18,2 running macOS 13.3 to a [LG 27 Inch UltraFine 5K](https://www.lg.com/us/monitors/lg-27md5kl-b-5k-uhd-led-monitor) monitor. I started IINA playing a video in full screen mode on the external monitor. IINA blacked out my MacBook Pro's display.

While the video was playing I then typed ⌘S to take a screen shot. I waited for the OSD to display `Screenshot Captured` (without preview). Then I pressed the space bar, pausing the video, to confirm the focus was still with IINA.

How does this compare to the scenario where it fails for you?

I also tested some with the video playing on the MacBook Pro's display and the external montor blacked out. Still didn't reproduce for me.

Although this could be some sort of elusive IINA defect, if you search the net for "mac loss of focus" you will see that often times it is traced to a malfunctioning background application. One post I read had traced it to an older version of Google Drive running in the menu bar. Think about if you have any background applications that could be focus stealers.

**Comment by beyondcompute** [comment]
Hello! I have `Use legacy full screen` disabled. IINA app actually doesn’t lose focus. Only the window somehow does. I tried to reproduce it without blacking out the other screens and it was still happening. It still said “IINA” in the menu bar but I needed to click the playing window to get the control back. No other visible windows of IINA were open.

I’ll update the issue description.

**Comment by beyondcompute** [comment]
@low-batt I found that the issue is likely caused by my machine’s exotic setup. So it’s probably not a problem with IINA. Hence closing this. Thank you for your work!
