### ISSUE TITLE
The software is so easy to use. When will the linux version come out?

### ISSUE THREAD

**Issue by hacker-zjd** [iina/iina#4275]
**What you want IINA to do:**

**What IINA does currently:**

**Why you think this should be added:**

**Examples of other projects that have something similar:**

Looking forward to the linux version！！！

**Comment by low-batt** [comment]
There is an official answer in the FAQ [Will there be a Windows/Linux/iOS version?](https://github.com/iina/iina/wiki/FAQ#will-there-be-a-windowslinuxios-version):
> No. See #674, #714 and #900.

Of course it is fine to ask if the situation has changed since that answer. Here is my _unofficial_ answer to that:

&nbsp;&nbsp;&nbsp;&nbsp;Yes, the situation has changed. It has gotten _worse_ (my opinion).

Before a project ever considers adding a platform the first question that should be asked is whether the primary platform is properly supported. Apple will intentionally break backward compatibility and expect application developers to adapt their applications to the changes. Big Sur was one of those macOS releases. IINA is still dealing with the fallout from that macOS release. Developers need to focus on macOS.

Ignoring that. The primary concern is that so much of the IINA code base is tied to macOS that support for another platform is really a separate project.

So sorry, there are no plans for a Linux version.
