### ISSUE TITLE
Add interface/module for Apple TV!

### ISSUE THREAD

**Issue by iptvchecker** [iina/iina#4393]
**What you want IINA to do:**
Add interface/module for Apple TV! This will allow the app to run/work on Apple TV. Other "paid!" IPTV apps for Apple TV are scams that want to take your money and run!

Create the framework to port to Apple TV.

**What IINA does currently:**
No interface/module for Apple TV! 

**Why you think this should be added:**
IINA does a great job running on mac laptops, so why not extend to Apple TV?

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
Although the FAQ [Will there be a Windows/Linux/iOS version?](https://github.com/iina/iina/wiki/FAQ#will-there-be-a-windowslinuxios-version) does not discuss Apple TV, the answer is still the same, sorry, IINA has no plans to support platforms other than macOS.

IINA is a graphical user interface for the [mpv](https://mpv.io/) player, specifically designed for macOS. Because so much of the code is tied to macOS the view of the team is that support for other platforms should be a separate projects.
