### ISSUE TITLE
Delay after hitting play button

### ISSUE THREAD

**Issue by koteukka** [iina/iina#4397]
**System and IINA version:**

- macOS 13.3.1(a)
- IINA  1.3.1

**Expected behavior:**

**Actual behavior:**
If wireless headphones are connected, video starts playing with a delay of about 3 seconds. Without headphones everything's alright. Seems like it started happening after installing Security Response 13.3.1(a). If I play a youtube video in Safari simultaneously it also works fine. 

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
Connect wireless headphones, play video

- [x] MPV does not have this problem.

**How often does this happen?**
Systematically

**Comment by low-batt** [comment]
There are multiple issues causing lagging. These problems have been addressed in the development version of IINA. If you know how to deal with an _unsigned_ build you can test the nightly build of IINA and see if the problem has been fixed. Nightly builds can be downloaded [here](https://nightly.iina.io/).

However, this issue reports two facts that are inconsistent with the known problems:
> Seems like it started happening after installing Security Response 13.3.1(a).

>  - [x] MPV does not have this problem.

The known lagging experienced when using wireless audio devices is the mpv issue https://github.com/mpv-player/mpv/issues/10270. The nightly IINA build uses a newer version of mpv that contains the fix for that issue.

I've not had a chance to install the security update. I will get that done and check for new lagging.

**Comment by koteukka** [comment]
Actually, this was a third-party software problem. An app ACE by Rogue Amoeba for Discord, that allowed to translate sound live was causing this issue in many apps. After reinstalling everything's fine. Sorry for bothering

**Comment by low-batt** [comment]
@koteukka I really appreciate that you took the time to post your findings.

From my point of view, if IINA is malfunctioning, it is a valid issue. Doesn't matter that the root cause turns out to be a defect in some other application. There are other issues here that are due to macOS Ventura or one of the libraries IINA is built on top of.

This is not the first time an IINA issue was traced to the [Rogue Amoeba](https://rogueamoeba.com/) Audio Capture Engine. After a lot of investigation issue #3478 was traced to ACE causing the macOS daemon `coreaudiod` to go crazy and make thousands of calls to the macOS power management daemon, running it out of memory. That ACE problem has been fixed.

I was unaware of this ACE problem and that it could slow down the start of wireless audio like this.  It is very helpful that you reported this. I now know to ask users if ACE is installed if they are experiencing lagging.
