### ISSUE TITLE
Touch Bar indicator will not update unless on-screen indicator is active

### ISSUE THREAD

**Issue by ericswpark** [iina/iina#4435]
I did search for this issue but didn't find anything, which is surprising given that it is very visible during normal use. If there is a duplicate please let me know so I can close this issue!

**System and IINA version:**

- macOS  Ventura 13.4 (22F66)
- IINA  1.3.1 Build 133

**Expected behavior:**

The Touch Bar indicator should update the current progress in real-time as the video plays

**Actual behavior:**

The Touch Bar indicator will freeze until the main, on-screen progress indicator comes up (by moving the mouse around, for example)

**Steps to reproduce:**

- Open any video file
- Enter full screen
- Start to watch the Touch Bar indicator
- Wait until the main, on-screen indicator (control bar?) disappears due to time-out

**How often does this happen?**

Always

**Comment by low-batt** [comment]
Thank you for reporting this.

I'm certain this is the problem described in issue #4058. This problem has been fixed in the development version of IINA. That fix will be included in the next release of IINA. As can be seen by the pinned issue the next release is nearing completion.

If you want to confirm this issues is fixed and know how to deal with an _unsigned_ build, nightly builds of the development version of IINA are available [here](https://nightly.iina.io/).

**Comment by ericswpark** [comment]
Great, thank you for the response @low-batt . Sorry about the duplicate report! Closing.

**Comment by low-batt** [comment]
Don't worry about entering a duplicate. Not a problem. A lot of the time it is hard to find duplicates in a search. Taking the time to enter an issue is very much appreciated.
