### ISSUE TITLE
Shortcut request: Playback menu - Jump to Beginning with pagedown ⇟

### ISSUE THREAD

**Issue by verityj** [iina/iina#4443]
**What you want IINA to do:**

It would be very convenient if IINA could have a shortcut to its menu item Playback - Jump to Beginning by simple pagedown key (⇟). 

EDIT: or a HOME key (fn ←).

(That is the closest I can think of to have it easy enough to remember as QuickTime jumps to beginning with option ← and jumps to end of file with option →. Right now I prefer to use QuickTime to quickly check the output after trimming off beginnings or endings of videos.)

**What IINA does currently:**

There is no default shortcut to jump back to the beginning of the current file. Current workarounds:
1. Create an application specific shortcut in System Preferences - Keyboard - Keyboard Shortcuts (mac-specific). Drawback - on my keyboard, pagedown is fn - ↓ and that cannot be assigned as a shortcut in the system.
2. IINA preferences - Key Bindings. Duplicate the IINA Default configuration and add a ⇟ key to "seek 0 absolute". Drawback - it would be great to see it in the menu bar to remember easier, as that's where the function is listed.

**Why you think this should be added:**

Ease of use and no need to learn to create custom IINA key binding configurations.

**Examples of other projects that have something similar:**

QuickTime: option - → and option - ← jumps to video beginning and end, respectively. (P.S. QuickTime really beautifully scrubs forward/back while playback is paused. Nothing seems to replicate that in IINA.)

**Comment by benungs** [comment]
I have a custom shortcut "seek 100 relative-percent" that jumps to the end of a video. And a second shortcut "seek -100 relative-percent" (note the minus sign in front of the number) that jumps to the beginning. I have these mapped to option+right and option+left, respectively, to mimic Quicktime player. Works as expected.

(I know you want this in the menus, and want to avoid key bindings, but just in case, you know, here it is)

**Comment by verityj** [comment]
Thank you! I learned something :) I see there are two options: `seek 100 relative-percent+exact` and `seek 100 relative-percent`. Do you know the actual difference between them?

What I could tell from my testing is that exact jumps immediately to the end of the file (and either stops playback or starts the next one). The non-exact jumps _almost_ to the end and plays the last few seconds. It seems.

**Comment by benungs** [comment]
I imagine "+exact" is the better way to do it, then.  I don't see why they wouldn't do the same thing, but I've never read the manual on this stuff, either. Thanks for the tip, and glad to help.

**Comment by low-batt** [comment]
On this:
> I see there are two options: seek 100 relative-percent+exact and seek 100 relative-percent. Do you know the actual difference between them?

The mpv manual for [seek](https://mpv.io/manual/stable/#command-interface-seek-%3Ctarget%3E-[%3Cflags%3E]) says:
> By default, keyframes is used for relative, relative-percent, and absolute-percent seeks, while exact is used for absolute seeks.

A primary goal of most of the various [video coding formats](https://en.wikipedia.org/wiki/Video_coding_format) is to reduce the size of the resulting digital video file. Priority is also given to playback in the forward direction.

Imagine 4 frames from a film based movie. Each frame is a picture of a ballpark. Nothing is moving except an airborne baseball moving in the sky. With a film based movie each frame is a complete separate picture. This could be converted to digital by encoding each frame separately as an individual picture. Trouble is the resulting digital version of the movie would be massive.

One of the techniques to reduce the size is to use keyframes and delta frames. Imagine we include a full picture for the first frame and instead of a full picture for the second frame we include instructions to erase the baseball in the first frame picture and draw sky there instead and then draw the baseball in a different position. And we do the same for the next two frames. Our digital version now consists of one full picture and 3 sets of changes to that picture in order to recreate each of the 3 following frames. We have greatly reduced the amount of space required for the digital version of this movie.

This is all fine for normal playback, but what if you tell the player to seek to a particular time and restart playback there? What does the player do if that time lands on a frame represented only by instructions on how to change the displayed picture? You would not want it to just display a baseball and a baseball sized bit of blue sky against a blank background. But that is all that is in the file for this point in time. To display a full picture you must find a frame that has a full picture and then apply changes until you have generated the picture for this frame.

Depending upon where the seek position lands and how the digital video was encoded seeking might be delayed while the player decodes many frames to display the frame at the specified point in time. A way to speed up seeking would be to find the nearest full picture (keyframe) and start playback from there. When you try and seek forward 5 seconds and you notice playback actually jumped forward 10 seconds, this is what is happening.

In the mpv documentation `keyframe` refers to this kind of seeking, where to speed up seeking it will restart playback at a full frame near the time specified, whereas `exact` tells the player it must restart playback at exactly the time specified.

The IBM tutorial [Keyframes, InterFrame & Video Compression](https://blog.video.ibm.com/streaming-video-tips/keyframes-interframe-video-compression/) is a good introduction to video compression.

**Comment by verityj** [comment]
Closing as I set a manual custom shortcut. Jumping is consistent now, to beginning and end, with alt/opt - arrows.
