### ISSUE TITLE
Unsupported external subtitle Error

### ISSUE THREAD

**Issue by stingusss** [iina/iina#4533]
**System and IINA version:**

- macOS Ventura 13.5 (22G74)
- IINA 1.3.2 Build 135

**Actual behavior:**
Getting Unsupported external subtitle Error for a specific subtitle file. It works well in VNC but not in the IINA for some reason.

**Steps to reproduce:**
Just try using the subtitle.

**How often does this happen?**
100% of the time

Here's the subtitle I'm having problem with:
[[Beatrice-Raws] Yahari Ore no Seishun Lovecome wa Machigatte Iru 05 [BDRip 1920x1080 x264 FLAC].ass.zip](https://github.com/iina/iina/files/12164004/Beatrice-Raws.Yahari.Ore.no.Seishun.Lovecome.wa.Machigatte.Iru.05.BDRip.1920x1080.x264.FLAC.ass.zip)

**Comment by low-batt** [comment]
The software industry has trouble writing and adhering to specifications. One aspect of this is that programmers add hacky workarounds to try and compensate for applications generating invalid files instead of fixing the broken applications.

For subtitles in [Advanced SubStation Alpha](https://en.wikipedia.org/wiki/SubStation_Alpha) format, IINA (through [mpv](https://mpv.io/)) uses the [libass](https://github.com/libass/libass) library. From the ASS specification referenced on the libass GitHub page:

> **2. The sections in a Sub Station Alpha script**
>
> **\[Script Info]**
> This section contains headers and general information about the script.
> The line that says “\[Script Info]” **must** be the first line in a v4 script.

The specification could not be clearer, if the file does not start with `[Script Info]` it is not a valid `.ass` subtitle file. That line is not optional, it **must** be present and it **must** be the first line.

The attached subtitle file violates that requirement and is therefore not valid: 
```text
; Script generated by Aegisub r7315
; http://www.aegisub.org/
[Script Info]
; Script generated by Aegisub 2.1.9
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
```

Rather weird that it has two "generated by" comments. If you edit the file and remove those first two extraneous lines then the subtitle file is accepted.

**Comment by stingusss** [comment]
Got it! Thank you!
