### ISSUE TITLE
<delete> does not remove files from the playlist

### ISSUE THREAD

**Issue by Shimushushushu** [iina/iina#4538]
**System and IINA version:**

- macOS Ventura 13.4.1 
- IINA 1.3.3 

**Expected behavior:**

Pressing &lt;delete&gt; removes the selected files in the playlist.

**Actual behavior:**

Nothing happens, except for an alert sound (the same as `printf "\a"`), and no crash occurs.

**Steps to reproduce:**

1. Open several files.
2. Choose arbitrary number of them in the playlist.
3. press &lt;delete&gt;. 

- [x] MPV does not have this problem.

**How often does this happen?**

Always, as long as the steps above are performed.

**Comment by low-batt** [comment]
Reproduced. Thank you for reporting this!
Confirmed IINA 1.3.2 works. This is a regression added in IINA 1.3.3.

From a very quick analysis…

This method was added to the `MainWindow` class in commit 0bc3691cf5805f51ddb491ee249c4d75e056d147:
```swift
  override func keyDown(with event: NSEvent) {
    /// Forward all key events which the window receives to its controller.
    /// This allows `ESC` & `TAB` key bindings to work, instead of getting swallowed by
    /// MacOS keyboard focus navigation (which we don't use).
    if let controller = windowController as? MainWindowController {
       controller.keyDown(with: event)
    }
  }
```

Adding debug logging to see the responder chain shows:
```text
<IINA.MainWindow: 0x10e6f2420>
<IINA.MainMenuActionHandler: 0x600003ea0030>
<IINA.MainWindowController: 0x11e886000>
```

The above code by passes `MainMenuActionHandler`. That prevents this method in `PlaylistViewController` from being called:
```swift
  @objc func delete(_ sender: NSMenuItem) {
    player.playlistRemove(playlistTableView.selectedRowIndexes)
  }
```

At least I think that is what is going on.

If the menu item is invoked directly the entry is removed from the playlist.

@svobs Please look into this one.

**Comment by svobs** [comment]
> The above code by passes MainMenuActionHandler. That prevents this method in PlaylistViewController from being called:
> At least I think that is what is going on.

If only it were that simple.

The `MainMenuActionHandler` class just contains extra actions for `MainWindowController` but doesn't really need to listen for input. It relies on the code in `MenuController` to bind keys from `MainWindowController` to those actions. (It doesn't really need to be its own separate object, really). The problem here is that the `PlaylistViewController` is being left out of the chain.

I unfortunately wasn't aware of cut/copy/paste/delete support in the Playlist until now. I had assumed that the sidebar didn't use any key bindings. So this complicates things.

The real problem is that AppKit has a special separate mechanism for handling what it considers "navigation" keys, and it's not straightforward and hardly anyone seems to know how it works or how to properly override it. These include the `UP` and `DOWN` arrow keys, `TAB`, `SHIFT+TAB`, and `ESC`. I tried to avoid it entirely by overriding `keyDown` in `NSWindow`. But it looks like `PlaylistViewController` needs to be first responder while it is visible. Not hard to do, and looks like that fixes the Edit menu items. But when I do that, the `TAB` and `ESC` stop working again...and `UP` ends up being responded to by the playlist table while `DOWN` goes to MainWindow's key bindings...

Actually, looks like even in IINA 1.3.2, that last problem existed: `UP` was used by the playlist, and `DOWN` was used by the window bindings. Will see if I can figure out how to properly deal with this...

**Comment by svobs** [comment]
Submitted a PR which gets Delete working again. Two steps forward, one step back...

The UP arrow key is still wonky. I took a few pot shots at it, but still no idea why. I will try to claim that's outside the scope of this defect because it was already broken... though it does work on my fork, so there's something to track down at some point.

**Comment by low-batt** [comment]
Fixed by PR #4569

**Comment by Shimushushushu** [comment]
Well ..., the delete key does work for now, but some other keys do not work as I expected, e.g., in the music mode the up/down keys were used to traverse items (before 1.3.4), but in 1.3.4 they raise/lower the volume.  But I think fixing key-bindings is possibly an endless work if you don't know all of them in advance.  Finally, thank you for the fix and I'll close the issue.

**Comment by low-batt** [comment]
Thanks so much for testing IINA 1.3.4, reporting the results and closing this issue. Very helpful.

On the actions of the UP and DOWN keys. If in IINA's settings under `Key Bindings` you have `IINA Default` selected then those keys are mapped to control the volume. Could be that was malfunctioning before, but the current IINA 1.3.4 behavior is correct.

There are still are problems in the area of key event processing. More fixes are planned.
