### ISSUE TITLE
Command H to hide Iina does not in (non-Legacy) Full Screen Mode

### ISSUE THREAD

**Issue by peterinjapan** [iina/iina#4573]
**System and IINA version:**

- macOS Ventura 13.4.1 (c) (22F770820d)
- IINA Iina 1.3.3

**Expected behavior:**

When in full screen mode, command H will not hide the app as expected. (It does work if Use Legacy Full Screen Mode is checked in General)

**Actual behavior:**

Typing command H, which should hide the app, just makes a beep if in Full Screen Mode with "use legacy full screen mode" off. This could lead to embarrassing situations of getting caught watching "certain multimedia files" for example. All apps should hide themselves (go into the background and hide all windows) if command H is pressed.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

Make sure Use Legacy Full Screen is off, watch a video, go to full screen mode, type command H to see Iina not hide itself as it would in any other case. It just beeps instead of disappearing, which is what we would want if the Boss comes in and sees us watching a video, for example.

- [ ] MPV does not have this problem.

**How often does this happen?**

All the time.

**Comment by low-batt** [comment]
The feature in question is covered in [The menu bar](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar) section of Apple's Human Interface Guidelines:

| Menu item | Action | Guidance |
| --- | --- | --- |
| Hide _YourAppName_ | Hides your app and all of its windows, and then activates the most recently used app | Use the same short app name you supply for the About item. |

The other related features are [Keyboard shortcuts](https://developer.apple.com/design/human-interface-guidelines/keyboards#Keyboard-shortcuts) and [Going full screen](https://developer.apple.com/design/human-interface-guidelines/going-full-screen).

From the above references we can see that pressing ⌘H is triggering the menu item `Hide IINA`. I could not find anything in the HIG that specifically discussed the behavior at issue. 

The sound you are hearing is probably `Boop`. That is the default macOS `Alert sound`. It is configurable in the macOS `System Settings` in the `Sound` section.

When the HIG does not provide guidance, the next step is to check the behavior of Apple's applications. This screenshot of [TextEdit](https://support.apple.com/guide/textedit/welcome/mac) in full screen mode shows the reason for the behavior in question:

![issue-4573](https://github.com/iina/iina/assets/86170219/55eb69ca-cc04-41c4-9e1b-0b3642c712c2)

As you can see the menu item `Hide TextEdit` is disabled. Pressing the shortcut key for a disabled menu item will emit the `Boop` alert.

IINA's behavior in this case is coming from AppKit/macOS. Apparently Apple requires you to exit full screen before you are able to hide an app. There are other ways to switch apps while in full screen mode. 

When the IINA setting `Use legacy full screen` is enabled the macOS provided full-screen experience is not used. Instead IINA's custom full-screen support is used. Apple supports applications using their own custom full-screen support as mentioned in [Going full screen](https://developer.apple.com/design/human-interface-guidelines/going-full-screen). But changes in macOS Big Sur completely broke IINA's custom full-screen implementation. It is limping again, but there are still problems that need to be addressed.

Because it is not using the built in support, AppKit does not "know" IINA is in full screen mode and keeps this menu item enabled. You could argue that IINA is in the wrong here as it is not matching what Apple's full screen mode does.

Anyway, my conclusion is that the behavior being reported is coming from Apple and is the expected behavior in this case.

**Comment by low-batt** [comment]
On the general macOS question about how to quickly switch away from an application that is in full screen mode using the keyboard…

I suggest looking into this macOS feature: [Work in multiple spaces on Mac](https://support.apple.com/guide/mac-help/work-in-multiple-spaces-mh14112/mac)
That feature allows you to switch between desktops by pressing: ⌃→ / ⌃← 

If you enable the macOS [Reduce motion](https://support.apple.com/guide/mac-help/reduce-screen-motion-mchlc03f57a1/mac) setting, switching between spaces is faster.

In the situation described you would want to press the ⏯ button to stop playback and then press ⌃→ to switch desktops.

**Comment by peterinjapan** [comment]
Ah, I see, so it's the default Mac OS behavior? It's not a problem then,
especially since there's the option to use Legacy. Thanks as always!

**Comment by low-batt** [comment]
Yes, this seems to be standard macOS behavior. I just tested QuickTime Player and it behaved just like TextEdit and IINA. The behavior comes from Apple's [AppKit](https://developer.apple.com/documentation/appkit) framework. The macOS provided full-screen experience referred to by the HIG comes from the  [toggleFullScreen](https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen) AppKit method.
