### ISSUE TITLE
API Quota warning on opening iina (Is it a phishing scam?)

### ISSUE THREAD

**Issue by andrewle8** [iina/iina#4617]
Hi,

I received this warning whenever i start iina now. 

Is it a phishing scan? When i press register it directs me to:
<img width="256" alt="Screenshot 2023-09-13 at 15 23 22@2x" src="https://github.com/iina/iina/assets/138733537/7df8b26e-2d2e-4bb0-87d9-3ddd964dfb50">

https://secure.assrt.net/user/register.xml?redir=http%3A%2F%2Fassrt.net%2Fusercp.php

I'm assuming it's from a subtitle? How can I remove this?

It doesn't seem to let me play any videos.

Thanks for the help! Love iina!

**Comment by low-batt** [comment]
Always a good idea to stop and investigate if phishing is suspected.

In this case the message shown is coming from IINA. 

In general, the various subtitle sites impose quotas on how many subtitles you can download in a certain amount of time. If you do not use an account then they will usually impose an even lower quota tied to your IP address. If your traffic is grouped in with others the quota may already be used up.

I'm not familiar with `assert.net`, so I'm having to guess a little, but I believe the above alert is warning that you have not set an API token for `assert.net` in IINA's settings on the `Subtitle` tab:
![assert-token](https://github.com/iina/iina/assets/86170219/4a3a7339-f435-4cea-a84e-b3963c8767c0)

Instead IINA is going to use a token that is only supposed to be used for demos. The reference to `network error` is likely because IINA's error reporting is rather poor and usually reports that error for various problems including the site denying a download due to a quota being exceeded.

Thus this prompt is all about warning that it is better to sign up with `assert.net` and obtain your own API token.

Normally this would not prevent videos from playing, just cause trouble with downloading subtitles. So I'm confused by the report that videos can't be played. Did you enable the IINA setting `Search online subtitles automatically`?

**Comment by andrewle8** [comment]
Thank you so much for clarifying. It turns out that all I had to do was restart my M1 Macbook Pro. I did have Search online subtitles automatically on. I am turning it off now. Thanks a ton for your help!
