### ISSUE TITLE
iina on phone ?

### ISSUE THREAD

**Issue by avichou** [iina/iina#4627]
is there any project to bring iina to phones, be it iOS or android ?

**Comment by low-batt** [comment]
The answer provided in the FAQ question [Will there be a Windows/Linux/iOS version?](https://github.com/iina/iina/wiki/FAQ#will-there-be-a-windowslinuxios-version) is…
> NO

The reason is that IINA is a full GUI for the [mpv](https://github.com/mpv-player/mpv) player specifically designed for macOS. Supporting other platforms would require so many changes that it is deemed better to implement that as a completely separate project.

 The mpv wiki contains a list of [GUI frontends](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv#gui-frontends). That page lists:
 - [Outplayer](https://apps.apple.com/us/app/outplayer/id1449923287) (iOS)
 - [mpv-andriod](https://github.com/mpv-android/mpv-android)

The author of Outplayer mentions being inspired by IINA.
