### ISSUE TITLE
Incompatible in MacOS 10.11.6

### ISSUE THREAD

**Issue by Zbynius** [iina/iina#4634]
Iina is stated to be compatible with macOS 10.11+ and when downloaded on El Capitan 10.11.6, the program icon is crossed out as a program not supported on that system.

- macOS 10.11.6
- IINA 1.3.3

**Comment by low-batt** [comment]
I've asked the other developers about this. Waiting for an answer. Stay tuned.

**Comment by Zbynius** [comment]
Last compattible version is 1.3.1.

**Comment by low-batt** [comment]
Confirmed. 

The [README](https://github.com/iina/iina#features) says:
> Designed with modern versions of macOS (10.11+) in mind

But the universal binary executable contains `10.13` for the minimum macOS version supported on Intel Macs:
```bash
low-batt@gag ~$ otool -l /Applications/IINA.app/Contents/MacOS/IINA | grep -E -A4 '(LC_VERSION_MIN_MACOSX|LC_BUILD_VERSION)' | grep -B1 sdk
  version 10.13
      sdk 13.3
--
    minos 11.0
      sdk 13.3
low-batt@gag ~$ 
```

Thus causing macOS 10.11 to cross out the program icon.

I confirmed this is also true for IINA 1.3.2 and that IINA 1.3.1 reports 10.11 for the minimum macOS version supported.

The documentation does not match the application, so confirmed BUG. But which is wrong?

I checked with the developers who would know, but they are super busy at the moment. They will eventually get back to me on this. The following is what I know about the situation…

The latest stumbling block with continuing to provide support for [OS X El Capitan](https://en.wikipedia.org/wiki/OS_X_El_Capitan) and [macOS Sierra](https://en.wikipedia.org/wiki/MacOS_10.12) is the following from the [Xcode 14 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes):
> Building for deployment to OS releases older than macOS 10.13, iOS 11, tvOS 11, and watchOS 4 is no longer supported. (92834476)

That means to build for 10.11/12 you must use Xcode 13. That is a huge problem due to the following from the [Xcode 13.4.1 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_4_1-release-notes):
> Xcode 13.4.1 requires a Mac running macOS Monterey 12. (Note: macOS Ventura 13 only supports Xcode 14 beta.)

To continue building with Xcode 13 you must not upgrade macOS.

This decision by Apple is likely a death blow for IINA's support of 10.11/12. The problem is that in reaction to Apple's decision the projects IINA is dependent upon will likely make changes that break support for these old versions.

IINA planned to continue support for 10.11/12 in IINA 1.3.x by building with Xcode 13 while also supporting Xcode 14. Then reconsider what to do for IINA 1.4.0.

This is decision by Apple is the reason behind the following entry in the [IINA 1.3.1 Release Notes](https://github.com/iina/iina/releases/tag/v1.3.1):
> **Deprecation Notice**
> Xcode 14 now only supports building for macOS 10.13 and above. We will work towards possible solutions, but please be aware that we may have to drop support for macOS 10.11 and 10.12 in future releases. IINA 1.3.1 might be the last version that supports macOS 10.12 Sierra.

I know there was trouble building the dependencies. The intent was to include [libjxl](https://github.com/libjxl/libjxl). It was dropped at the last minute due to 10.11 not containing the runtime libraries required by the C++ version required to build that library. There might have been other problems that I am not aware of.

I checked the current dependencies using:
```text
find . -name '*.dylib'| xargs -I% otool -l % | grep -E -A4 LC_VERSION_MIN_MACOSX | grep version
```

That showed all of the libraries support 10.11 for the minimum macOS version. I can not explain why the application was built to require 10.13+. Maybe there is some other consideration I am not aware of.

Note that as it was support for 10.11 was starting to crumble. Issue #4062 reports a very concerning crash that we can't explain.
