### ISSUE TITLE
Failed to download subtitles from assrt due to rate limit.

### ISSUE THREAD

**Issue by jjaychen1e** [iina/iina#4671]
**System and IINA version:**

- macOS 14.0
- IINA 1.3.3 Build 138

**Steps to reproduce:**

1. Use assrt as source of subtitles
2. Choose a subtitle resource with more than 2 subtitles (which means there are more than 2 subtitles in the `filelist`, usually this happens when the resource contains subtitles for the whole season, rather than one episode)
3. It should pop up a hint to display the download task is failed.

**Cause analysis:**

After validating the API and server ability of assrt, this issue is in the IINA side. When use proxy tools such as Proxyman, it's easy to guess the assrt server limits the concurrency requests.

**How often does this happen?**

Quite often

**Comment by jjaychen1e** [comment]
#4672 is not the perfect solution but it works well, because it would take seconds to download all subtitles. Maybe we could provide a window selector for users to pick files they want to download.

**Comment by low-batt** [comment]
Hello from a junior IINA developer. Thank you for reporting this and especially for posting a pull request with a fix.

On this:
> Maybe we could provide a window selector for users to pick files they want to download.

That is what `SubChooseViewController` is supposed to do? I'm only familiar with the code for [Open Subtitles](https://www.opensubtitles.org/en/search/subs). In `OpenSub` a `Subtitle` instance is associated with one subtitle file. In `Assrt` the `Subtitle` class contains a `fileList` property.  I know nothing about  this site's API so I'm not understanding why there are multiple files. Maybe the same subtitles are available in different file formats?

In any case at this time a more important consideration is this code:
https://github.com/iina/iina/blob/aa5a4158cef44e972c8515c2a723db14bc97bd83/iina/OnlineSubtitle.swift#L102-L105

The built-in online subtitle provider code is now considered [legacy code](https://en.wikipedia.org/wiki/Legacy_code). This is because the plan is to switch to plug-ins for such implementation. The plug-in system is included in the current release of IINA, but is disabled as it is not quite ready to be officially released. The plan is to enable it in the upcoming feature release.

Given that, enhancements such as adding a window selector probably should be done as a part of the plug-in conversion.

Open Subtitles is shutting down their XMLRPC API at the end of 2023. I am currently finishing changing the current Open Subtitles legacy code to switch to their new REST API. This is a temporary stopgap solution that may end up going straight into the trash if a plugin implementation can be created in time to meet the deadline.

I'm thinking IINA should not rush the feature release. Given the limited time left in the year I plan on proposing that IINA release a maintenance release before starting to work on the feature release. I will add PR #4672 to the fixes that should be included in this release. Of course it will be up to the senior developers as to what plans are appropriate to adopt.

**Comment by low-batt** [comment]
@lhc70000 has merged a tweaked version of the proposed fix into the `develop` branch.

**Comment by low-batt** [comment]
This has been fixed in IINA 1.3.4.

Thanks @jjaychen1e for the fix!
