### ISSUE TITLE
Pinch to Adjust video size shift the window position

### ISSUE THREAD

**Issue by sorae42** [iina/iina#4681]
**System and IINA version:**

- macOS 14.2
- IINA 1.3.3 Build 138

**Expected behavior:**

Pinching should not be moving the window position.

**Actual behavior:**

Pinching will move the window position as shown below:

https://github.com/iina/iina/assets/34794115/f6c24770-6096-427d-8bc1-025050f861f2

Moving the fingers also make this problem happens in a larger scale.

**Steps to reproduce:**

Enable Pinch to Adjust Windows Size and pinch a few times.

- [x] MPV does not have this problem.

**How often does this happen?** Always

**Comment by svobs** [comment]
Yes this is a problem. During the pinch gesture each minor adjustment triggers a resize calculation, which adjusts the window position accordingly. But each time it does the calculation there are tiny imprecisions, and these add up. The solution is to save the window position when the pinch starts, and use that as the base of each calculation, instead of using the current window position each time.

**Comment by anohren** [comment]
Good to see someone reported this and that the suggested solution is on point.

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0-beta1.
