### ISSUE TITLE
Phantom "B" tick appearing in play slider when AB-Loop is used

### ISSUE THREAD

**Issue by svobs** [iina/iina#4705]
**System and IINA version:**

- macOS 14.1.1
- IINA 1.3.3 dev build aa5a4158cef44e972c8515c2a723db14bc97bd83

**Expected behavior:**

A and B ticks in playback position slider should match timestamps of `ab-loop-a` and `ab-loop-b` properties , respectively, if and only if each is set.

**Actual behavior:**

B tick appears when `ab-loop-b` is not set, seems to be in an arbitrary spot, and may not even be inside the slider.

![SCR-20231202-rmfr](https://github.com/iina/iina/assets/2213815/b2167ca7-6999-4e55-bcbb-3235a0e9c196)
![SCR-20231202-rnbc](https://github.com/iina/iina/assets/2213815/900ee8bb-81a6-42c8-85bc-e6a5992c5ac7)

**Steps to reproduce:**
1. Open a video file in IINA. Set a key binding with action `ab-loop`.
2. In the player window, seek to >50% of the file's duration, and then pause.
3. Press the key for the `ab-loop` binding. See if the B tick appears at some distance to the right.
4. Seek to another spot in the video and activate `ab-loop` again. See if a third tick appears.
5. Try again with "floating" OSC but seek almost to the end. B tick will be outside the OSC.

- [NA] MPV does not have this problem.

**How often does this happen?**

Doesn't seem to happen at the beginning of the file, or is at least not as bad. But happens most of the time.

**Comment by low-batt** [comment]
Reproduced for me under macOS 14.1.2. So far I've not been able to reproduce this on my other Mac running macOS 13.6.1.

Setting a breakpoint in the `draw` method of the `PlaySliderLoopKnob` class confirmed this guard statement is being executed when drawing the `abLoopBKnob` knob:
```swift
guard !isHiddenOrHasHiddenAncestor else { return }
```

The `abLoopBKnob` knob is not being drawn and yet two knobs are visible.

If you try and drag the loop knobs, only the first one is draggable. Attempts to drag the second loop knob move the primary knob. That means the `mouseDown` method in `PlaySliderLoopKnob` determined the cursor was not in the knob's frame.

When you drag the first knob the second knob moves with it. The space between the knobs increases as the first knob moves to the right. Eventually the second knob moves outside of the slider.

That is what I have determined so far.

**Comment by low-batt** [comment]
The `draw` method in `PlaySliderLoopKnob` is being called twice with different values for `dirtyRect`. I have confirmed this does not happen in macOS Ventura. Not sure if this is a defect in macOS Sonoma or an intentional change. We know `NSSlider` is being changed for macOS 14.2 because of reports of the slider being broken in Beta 4. That has been fixed for the RC.

I will revisit this once macOS 14.2 is released.

**Comment by svobs** [comment]
> I will revisit this once macOS 14.2 is released.

Sounds good.

In retrospect, considering all the work that went into customizing every aspect of this slider, it's unfortunate that it wasn't just written from scratch using, say, Core Graphics. It wouldn't be nearly as likely to break unexpectedly, and it would be an order of magnitude faster to draw. In general these NS* classes seem to be very bug-prone and very slow. Yet there is no roadmap for SwiftUI replacements.

**Comment by low-batt** [comment]
Reproduced with macOS Sonoma 14.2.

I will have to take another look at this one.

**Comment by low-batt** [comment]
From a quick test, if I set [clipsToBounds](https://developer.apple.com/documentation/appkit/nsview/4236466-clipstobounds) to `true` the problem does not reproduce. Need to take a closer look as to why clipping is required.

**Comment by svobs** [comment]
> The draw method in PlaySliderLoopKnob is being called twice with different values for dirtyRect.

> From a quick test, if I set [clipsToBounds](https://developer.apple.com/documentation/appkit/nsview/4236466-clipstobounds) to true the problem does not reproduce. Need to take a closer look as to why clipping is required.

This makes sense in the context of `dirtyRect`, as we discovered in #4638. But I don't see `dirtyRect` being used directly. Does it change the value of `knobRect`?

If it works, I say just set `clipToBounds` to `true` and call it a win.

**Comment by low-batt** [comment]
I have always found that it is good to probe some more if you can't explain why a fix works. There have been a few times when further investigation uncovered other problems. This proved to be one of them. I implemented this back in 2021, so I'd forgotten the details. I finally had time to focus today and I tracked down what is happening.

Turns out this problem is good news. Apple fixed `NSSlider`. This problem is a result of the workaround I had to do due to  `NSSlider` not drawing subviews. I will post a fix shortly.

Sure glad you noticed and reported this one!
