### ISSUE TITLE
Need a larger exit icon on IINA play interface.  

### ISSUE THREAD

**Issue by vonseg1** [iina/iina#4710]
**What you want IINA to do:**
I want more than a tiny "x" button in the upper left of the playback interface.  It is difficult to put the mouse on it due to its small size.  

**What IINA does currently:**

**Why you think this should be added:**
Mouse control in most cases is not fine enough to put the cursor over the "x" button to stop the IINA app. without very careful mouse movement.

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
I'm not a graphical user interface programmer, so I'll be deferring to other IINA developer's on this one. But here are some thoughts from me…

The red, yellow and green buttons are a standard macOS thing. Searching the net you will find many posts such as the Apple Support Community post [how to make the window close button larger](https://discussions.apple.com/thread/6238890) from years ago. The usual advice is to use the keyboard instead of the mouse. They are suggesting using the key strokes documented in [Move and arrange app windows on Mac](https://support.apple.com/guide/mac-help/work-with-app-windows-mchlp2469/mac):
> ## Close one or all windows for an app
> On your Mac, do any of the following:
> - Close a single window: In a window, click the red Close button  in the top-left corner of the window, or press Command-W.
> - Close all open windows for an app: Press Option-Command-W.
> 
> Closing one or all windows for an app doesn’t quit the app—it remains open (indicated by the small dot below the app’s icon in the Dock). To quit the app, press Command-Q. See [Quit apps](https://support.apple.com/guide/mac-help/quit-apps-mchl834d18c2/14.0/mac/14.0).

With IINA the default key bindings bind `q` to the `mpv` `quit` command. So pressing `q` when the player window is in focus will quit IINA.

I do not do that. I too like mice. I use MX Master and MX Anywhere mice from [Logitech](https://www.logitech.com/en-us/products/mice.html). Maybe because I'm so used to it I do not have trouble using the mouse to close a window by pressing the red button. Although the Logitech mice are good with a lot of surfaces I do find it is hard to be accurate with them on certain surfaces.  Adjusting the tracking speed in the macOS system settings may help. Assuming you have a Logitech mouse you can try installing [Logi Options+](https://www.logitech.com/en-us/software/logi-options-plus.html). That does improve the precision of the mouse. I have it installed on the Mac I'm typing this on. I have had problems with this software in the past, but not with the version I'm currently using.

**Comment by vonseg1** [comment]
I will call this issue closed.  Thank you for the detailed response.  

Do I close the issue, or do you?  I am new to the GitHub Community.

David von Seggern


 

    On Wednesday, December 6, 2023 at 12:36:15 AM EST, low-batt ***@***.***> wrote:  
 
 


I'm not a graphical user interface programmer, so I'll be deferring to other IINA developer's on this one. But here are some thoughts from me…

The red, yellow and green buttons are a standard macOS thing. Searching the net you will find many posts such as the Apple Support Community post how to make the window close button larger from years ago. The usual advice is to use the keyboard instead of the mouse. They are suggesting using the key strokes documented in Move and arrange app windows on Mac:


Close one or all windows for an app

On your Mac, do any of the following:
   
   - Close a single window: In a window, click the red Close button in the top-left corner of the window, or press Command-W.
   - Close all open windows for an app: Press Option-Command-W.

Closing one or all windows for an app doesn’t quit the app—it remains open (indicated by the small dot below the app’s icon in the Dock). To quit the app, press Command-Q. See Quit apps.


With IINA the default key bindings bind q to the mpv quit command. So pressing q when the player window is in focus will quit IINA.

I do not do that. I too like mice. I use MX Master and MX Anywhere mice from Logitech. Maybe because I'm so used to it I do not have trouble using the mouse to close a window by pressing the red button. Although the Logitech mice are good with a lot of surfaces I do find it is hard to be accurate with them on certain surfaces. Adjusting the tracking speed in the macOS system settings may help. Assuming you have a Logitech mouse you can try installing Logi Options+. That does improve the precision of the mouse. I have it installed on the Mac I'm typing this on. I have had problems with this software in the past, but not with the version I'm currently using.

**Comment by uiryuu** [comment]
@vonseg1 I'll close this issue for you, don't worry.
