### ISSUE TITLE
build with the latest translations from crowdin

### ISSUE THREAD

**Issue by ShlomoCode** [iina/iina#4742]
I'm working on translating iina into my language (Hebrew), how can I build the application locally on my computer with the latest translations from crowdin, to check that I didn't make a mistake in the context, etc., without waiting for a new release?
Thanks

**Comment by ShlomoCode** [comment]
also i hope iina has RTL support

**Comment by uiryuu** [comment]
Thank you for contributing to IINA!

If you want to test the current translations on Crowdin for a certain language (Hebrew in your case), you can download the archive for your langauge:

![image](https://github.com/iina/iina/assets/20237141/b0508020-142a-4bca-9788-32037b855f99)

Then unarchive the zip file, you will get `[iina.iina] develop / iina / he.lproj`. Then navigate to the IINA source code folder, copy the `he.lproj` folder  into `iina/iina`. If conflicts happen, select overwrite.

After that, open Xcode and the IINA project. From the left sidebar, select the top most 'iina' entry, you will see the project info in the middle of the Xcode window. Click the + button:

![Untitled](https://github.com/iina/iina/assets/20237141/d07dc6bc-5ef5-41a6-9e1b-16fc6006992f)

Find Hebrew in the menu, click finish. You may encounter some warning dialogs, just ignore them.

Note that if your language is already enabled by IINA, you don't have to add the language into the project. Just copy, paste and overwrite the `.lproj` folder and compile IINA, you will have the latest translations from Crowdin.

Now you can compile the project and it will run in your system's locale. For how to compile the project, please refer to the readme file: https://github.com/iina/iina?tab=readme-ov-file#building

> also i hope iina has RTL support

Currently IINA doesn't have any RTL language localization enabled. You can contribute them in Crowdin though, but they are not enabled because they are not completed enough. I just tried to compile IINA in Hebrew, here's how it looks in one of the settings page:

![telegram-cloud-photo-size-5-6098426984624416594-y](https://github.com/iina/iina/assets/20237141/839ba3f6-518e-4656-ab22-c5535cb2af9d)

This is not intentionally supported by devs, but AppKit automatically transforms the current layout into RTL. I don't know whether or not this looks sane to RTL people. And there should be a lot of UI glitches in RTL, please report them via issues so that the devs can fix them for RTL languages.

**Comment by ShlomoCode** [comment]
> If you want to test the current translations on Crowdin for a certain language (Hebrew in your case), you can download the archive for your langauge:

I don't see a download button 🤔
![CleanShot 2024-01-14 at 01 19 39@2x](https://github.com/iina/iina/assets/78599753/59f06605-2671-440d-8407-878471f31120)
Maybe it depends on permission?

**Comment by uiryuu** [comment]
A major overlook of me. Given that Crowdin doesn't allow translators (who are not admins) to build and download the translated strings, I'm afraid that there's no way to preview the translations.

**Comment by ShlomoCode** [comment]
@uiryuu Maybe you can send me the current file here now and I will fix and translate?
It should be 2-3 rounds :)

**Comment by uiryuu** [comment]
[IINA (he).zip](https://github.com/iina/iina/files/13931637/IINA.he.zip)

**Comment by ShlomoCode** [comment]
@uiryuu I now tried to build with the Hebrew language (in the end I didn't have to use the zip file you sent - I suddenly discovered that your bot had already managed to pull the latest translations, so in fact I'm using the exact same files of the develop branch here),

I followed the instructions and added the language and Hebrew and set it as default, but in practice everything appears in English (even though I translated 84% of the strings)

A video is attached, I would appreciate it if you could explain to me what I missed... Thanks!
https://github.com/iina/iina/assets/78599753/60a4268a-018b-4b50-96df-f4a0361d3ec8

**Comment by uiryuu** [comment]
@ShlomoCode I think for the most of the parts, you are doing right. After enabling the Hebrew localization, you have to start in Hebrew. There are 2 ways of doing that:
1. Change your system language to He
2. Click edit scheme here:

<img width="236" alt="image" src="https://github.com/iina/iina/assets/20237141/2000fb89-aac4-426b-81c2-a4a98288d042">

Then navigate to Options, select Hebrew in the App Language drop down menu. Then click close. Recompile the project, you will have IINA running in Hebrew.

<img width="943" alt="image" src="https://github.com/iina/iina/assets/20237141/8ccdd7b7-cd0c-4943-9bfc-127c52fcba59">


> I suddenly discovered that your bot had already managed to pull the latest translations,

The `l10n_develop` is not up-to-date, the synchronization is manually triggered. So new translations after the creation date of the branch will not be in that branch. But yeah, you can use that for testing purposes, just be noted that it is not up-to-date. If you need more up-do-date translations, I can do the synchronization again.

**Comment by ShlomoCode** [comment]
@uiryuu I went through all the settings screens and corrected translations (95% of the strings are complete!)
Can you update the translations on GitHub or provide an updated zip?

What about RTL layout issues, will I create a new focused issue for that?

**Comment by uiryuu** [comment]
[IINA (he).zip](https://github.com/iina/iina/files/13944274/IINA.he.1.zip)

I wanted to sync the branch again, but there's some problem with the configuration preventing me from syncing the branch, which I will fix later.

> What about RTL layout issues, will I create a new focused issue for that?

Yes, please file an issue for that.

**Comment by ShlomoCode** [comment]
@uiyuu Thanks

Why are there certain translations that I already translated in crowdin 10 days ago, but when I build with XCode the strings are displayed in English?

For example the tab titles:
![CleanShot 2024-01-16 at 03 56 46@2x](https://github.com/iina/iina/assets/78599753/e3da3076-52aa-468a-86d3-9fcc39733693)

or the items in the toolbar:
![CleanShot 2024-01-16 at 03 55 07@2x](https://github.com/iina/iina/assets/78599753/41b20c01-1ee8-43c9-895f-ed77a5871556)

**Comment by uiryuu** [comment]
These are from `Localizable.strings`. Please go to `Localizable.strings` under iina/Assets, then on the right panel, you will notice that the checkbox for Hebrew is not selected. Click on it and then click "Use file", and recompile.

![image](https://github.com/iina/iina/assets/20237141/ee1aa556-8b1f-47f0-b524-204ceff59fc8)
![image](https://github.com/iina/iina/assets/20237141/91b852ee-7353-47d0-a283-46085e137ede)

**Comment by ShlomoCode** [comment]
@uiryuu This did solve the problem 👌

Interestingly, there is one case that is still presented in English, when adding an audio filter:
![CleanShot 2024-01-16 at 05 16 24@2x](https://github.com/iina/iina/assets/78599753/213bb027-0452-492f-8a5c-ec68edd6d370)
this translated 9 days ago: https://crowdin.com/editor/iina/11/en-he?view=comfortable#115

**Comment by uiryuu** [comment]
<img width="355" alt="image" src="https://github.com/iina/iina/assets/20237141/8a66c1c9-2d3a-4ebb-a965-8678af40dd4e">

Please also check the Hebrew language for this file. Sorry didn't give you the full list upfront, I didn't enable a new language for so long that I forgot some of the steps. I think those are all.

**Comment by ShlomoCode** [comment]
I actually only have 25 strings left to completely complete the translation 😁 

@uiryuu If I may ask about some translations that I was unable to do:

- [Display subtitles in letterboxes while in full screern](https://crowdin.com/editor/iina/57/en-he?view=comfortable#1947) - I didn't understand what "letterboxes" was and when I turned it on I didn't see a change in the display
- [Table View Cell](https://crowdin.com/editor/iina/71/en-he?view=comfortable#2897) - I didn't find such text in the log viewer
- [Box](https://crowdin.com/editor/iina/68/en-he?view=comfortable#2696) - missing context
- [Medium Light](https://crowdin.com/editor/iina/59/en-he?view=comfortable#2151)
- https://crowdin.com/editor/iina/27/en-he?view=comfortable#687, https://crowdin.com/editor/iina/27/en-he?view=comfortable#689 - full of variables, I didn't understand how to translate

maybe you should also add the context in crowdin, for the benefit of the following translators.

**Comment by uiryuu** [comment]
@ShlomoCode 

For the first and the forth one, I've left some comments in the crowdin, please check the comments. Things like "Table View Cell" and "Box" are just placeholders and will not ever displayed to users, therefore no need to translate, or just literal translation is fine. 

For the last one, the word between each '#' and '/' pair can be included in the string or not depending on the value of the variable. Basically "Seek {{#fwd}}forward{{/fwd}}{{#bwd}}backward{{/bwd}}" contains 2 variables, namely "fwd" and "bwd". If "fwd" is true and "bwd" is false, then only "forward" will be in the string, making the whole string "Seek forward". If "bwd" is true and "fwd" is false, the string will be "Seek backward".

**Comment by ShlomoCode** [comment]
@uiryuu Now I have to submit a PR that activates the Hebrew support so that it will be included in the next version, or do you prefer to wait for the corrections in the RTL display to be made before activating the option?
