### ISSUE TITLE
File loop keybinding not working in current version

### ISSUE THREAD

**Issue by caleidoscopio** [iina/iina#4841]
I cannot create a working keybinding for the file loop command.

I added this keyboard shortcut but it doesn't do anything when I press it.

<img width="513" alt="image" src="https://github.com/iina/iina/assets/73276364/ed3fe4c0-65a5-490f-8bac-e9dac6e6fc2c">

**Comment by low-batt** [comment]
I will be labeling this as bug due to poor error reporting. Checking the IINA log file shows the following errors:
```text
19:50:58.380 [iina][e] Return value -4 when executing key command loop-file
19:50:58.380 [mpv][e] [input] error: Command 'loop-file' not found.
19:50:58.381 [mpv][e] [input] error: Command was defined at main.
```

This was logged by the method `handleKeyBinding` in `PlayerWindowController`. Good to log the error, but this code should display an alert like is done if an invalid `mpv` option is added to the `Additional mpv options` setting in IINA's advanced settings.

As for why this is triggering an error…

From the `mpv` manual entry for [loop-file](https://mpv.io/manual/stable/#options-loop):
> --loop-file=<N|inf|no>, --loop=<N|inf|no>
>
> Loop a single file N times. inf means forever, no means normal playback. For compatibility, `--loop-file` and `--loop-file=yes` are also accepted, and are the same as `--loop-file=inf`.

This is a `mpv` _option_, not a `mpv` _command_.

This can be changed using the `mpv` [cycle-value](https://mpv.io/manual/stable/#command-interface-cycle-values) command like so:
```text
cycle-values loop-file "inf" "no"
```

**Comment by caleidoscopio** [comment]
Thank you, @low-batt. 

Using [cycle-value](https://mpv.io/manual/stable/#command-interface-cycle-values) worked.

However, when I use this shortcut there's no OSD overlay, nor does a checkmark appear in the Playback menu. One should appear saying File loop: on-off. 

My workaround was using the macOS system shortcuts.

**Comment by low-batt** [comment]
That an OSD message is not shown is a defect.

In the `Playlist` menu the checkmark appears next to the `File Loop` menu item for me. But the button on the `Playlist Panel` does not reflect that looping is enabled. So something is broken.

@uiryuu has been working on the playlist. I will mention this to him.
