### ISSUE TITLE
Cannot Pull Subtitles From Online Sources

### ISSUE THREAD

**Issue by Yell0whead** [iina/iina#5002]
**System and IINA version:**
- macOS Sonoma 14.5 (23F79)
- IINA 1.3.5 Build 141 (mpv 0.35.0-419-gf79458476b-dirty) (FFmpeg 6.0)

**Expected behavior:**
Going to Subtitles > Find Online Subtitles from... > (Select a download source), should pull a window with subtitle download options.

**Actual behavior:**
Completing the above produces no result. No window appears to select subtitles to download.

<details>
<summary><b>Crash report:</b></summary>

```
```
*Deleted crash report*

</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
*Deleted mpv log*

</details>

<br>

**Steps to reproduce:**
1) Open IINA
2) Load a video without subtitles
3) Select in the menu Subtitles > Find Online Subtitles from... > (select a download source)
4) If seeing the same error, I believe no subtitle download window will appear (giving various subtitle download options)

Unfortunately I do not have enough technical knowledge to properly download MPV for an M1 Mac to test, as it does not seem to be readily available.

**How often does this happen?**
This has been occurring for at least a few weeks, every time.

**Steps to troubleshoot:**
A) Have tried using a VPN
B) Have tried redownloading IINA
C) Have tried using earlier versions of IINA
D) Have tried creating a new OpenSubtitles.com account
E) Have tried fix #4090, which simply results in the following error:
![image](https://github.com/iina/iina/assets/107513780/67258131-f7ca-4c79-810f-a83ca24ba6db)

**Comment by low-batt** [comment]
In IINA's settings on the `UI` tab in the section `On Screen Display` is the setting `Enable OSD` checked?

The online subtitles feature uses the OSD, so if it is disabled, nothing happens. That is my first guess as to what is going on. This is considered a defect and in a future version the messages for downloading subtitles will still be displayed even if the OSD is disabled.

This issue is not related to #4090. No need to apply the workaround in that issue. The workaround is not working and giving an error because the `sub-auto` option needs to be set to a value like `fuzzy`. From the above error message it is being set to `value`, which is invalid. But no need to correct it as it is not related to the issue at hand.

**Comment by Yell0whead** [comment]
Ah @low-batt, you nailed it. Feel a bit silly!

That was 100% the issue, and your suggestion restored the expected behaviour. I would agree that including some indicator for when OSD is disabled, would be an ideal design choice. 

Thanks for your help.

**Comment by kokuken85** [comment]
i have a problem today. I can see all those. 
but i can not download any Subtitles. i tried different movies and tv shows. It says Network Error!  can anyone help?? @low-batt 

OS 15.3.  IINA 1.3.5

**Comment by low-batt** [comment]
Because of past problems this area of IINA 1.3.5 has extensive logging. With a log file I can tell what is happening. See: [How to collect log files when reporting an issue?](https://github.com/iina/iina/wiki/FAQ#how-to-collect-log-files-when-reporting-an-issue)

However it is likely that the problem is that the Open Subtitles servers are overloaded.

I just tested downloading and my first attempt failed:
```text
20:37:50.703 [onlinesub][e] Failed to obtain subtitles for file:///Users/low-batt/Movies/Armageddon.mp4 from opensubtitles.com. Login failed, API rate limit exceeded
```

What "API rate limit exceeded" means is that the Open Subtitles server thought API requests were being sent at too high of a rate from my IP address. However I received that response to the first API request. Troubling as I don't think I am behind a shared IP address.

Anyway, I retried and all worked.

If you share a public IP address with a lot of others, such as when using a school's network, a companies network or a VPN then if multiple people are using Open Subtitles along with you the servers might view it as one person making too much use of the service.

Last I heard there were 3 ways to use Open Subtitles:
- Logged into a paid VIP account
- Logged into a free account
- Not logged in

**Note** that accounts must work with opensubtitles.com, as opposed to the old web site, opensubtitles.org.

An advantage of a paid VIP account is that upon login you are switched to private servers dedicated to VIP users. They are less likely to be overloaded than the public servers. A VIP account also has a large download quota.

An advantage of a free account is that the download quota Open Subtitles imposes is based on your account, not your IP address. This response from Open Subtitles shows I used 1 out of my 20 allowed downloads and my quota will reset back to 20 in a little over 22 hours from now:
```text
  "reset_time" : "22 hours and 18 minutes",
  "remaining" : 19,
```

The typical problem with accessing Open Subtitles without a login is that you are behind a shared IP address and somebody else has already used up the daily download quota.

At least I think this is how things work. Of course Open Subtitles is the authority on how their site and accounts work.
