### ISSUE TITLE
Build System: Move libmpv out of the project

### ISSUE THREAD

**Issue by ghost** [iina/iina#508]
This would make it easier to build and therefore encourage more active users.

- Remove the `/iina/libmpv` folder.
- Link to Homebrew's `/usr/local/` libmpv dylibs & headers.

Then people can just:

- Take this source repo.
- Run brew install (or upgrade) mpv.
- Build this repo with their latest mpv. And to update later, just "brew upgrade --fetch-HEAD mpv" and rebuild iina without needing to copy any files. No need to constantly copy headers/dylibs.

It would also shrink the size of this repo (including dylib binaries in the source tree is bad).

Thoughts? :)

**Comment by saagarjha** [comment]
While I'm in agreement with the principle, I'm guessing that using the latest version of mpv will probably introduce breaking changes and merge conflicts.

**Comment by alejx** [comment]
IINA is supposed to be an out-of-box app. Not all users even know homebrew. And we have the responsibility to maintain the project when mpv API changes. In my opinion it is not a good idea.

**Comment by HarukaMa** [comment]
As long as the releasing .app / .dmg contains all libraries. We generally don't want the app relying on unknown environments, as we already made a mistake on VapourSynth support. If we can rely on that, we already have that one built in...

Also, please don't rely on homebrew too much since we do in some instances have to build mpv from scratch. I, for example, build ffmpeg myself, therefore cannot install mpv from homebrew (dependency issues, don't really want to force ignore that to prevent more potential problems). Current dependency copying script is already bugging me.

However keeping those binaries is indeed good (however `.git` cannot be saved anymore...). Maybe submodules?

**Comment by SteveJobzniak** [comment]
@HarukaMa Definitely. All binary releases should include all dylibs and libmpv etc so that users get a known-stable environment.

I just meant for development.

@saagarjha There wouldn't be breaking changes if we build mpv @ specific version tags or specific commits. I wonder if Homebrew can be told to checkout specific commits in --HEAD mode though. That would solve everything.
