### ISSUE TITLE
Seeking in macOS Sequoia beta 4 freezes

### ISSUE THREAD

**Issue by PsychoSid** [iina/iina#5088]
Obviously an FYI as beta software etc. so more for awareness.

Seeking forward / backwards with the latest Sequoia freezes video playback with 1.3.5 (pretty sure this is an OSX thing as I think VLC does this too)

Improved with the latest nightly but feels a little "off" :)

**Comment by jimmyorz** [comment]
Same issue here
But this will also happen when the file is just opened, or pause then play
0:08 and 0:37

https://github.com/user-attachments/assets/44872881-f35b-4458-a059-f7df4530b532

**Comment by PsychoSid** [comment]
I think it's better with "Hardware Decoding" disabled from the small chance I have had to check/test

**Comment by jimmyorz** [comment]
> I think it's better with "Hardware Decoding" disabled from the small chance I have had to check/test

I just disabled hardware decoding, but the IINA freeze still happen

**Comment by PsychoSid** [comment]
Yes mine too, I think I jumped the gun with that statement. Sorry. But the nightly seems better for sure.

**Comment by krackers** [comment]
Could either of you share the log file, as well as the hardware you are on? Both VLC and mpv use `CAOpenGLLayer`, so if there are issues cropping up seen on both it is worrying. Especially so because with m1 chips at least the OpenGL parts are translated to metal, so there's not much room for things to go wrong unless apple is letting the translation layer rot which would be worrying.

(It could also be something not opengl specific but still as serious, perhaps related to cvdisplaylink timings.)

**Comment by low-batt** [comment]
There were problems with hanging during the Ventura Betas due to macOS regressions that it took Apple a while to fix. Likely this is also a macOS regression, but it is always good to investigate and make sure there isn't something IINA is doing wrong.

In the screen capture posted above I saw a [spinning wheel of death](https://en.wikipedia.org/wiki/Spinning_pinwheel). That means the main thread is blocked. To debug that we need to see a process sample taken when IINA is in that state. This should provide an indication as to why the main thread is blocked.

To collect this evidence first enable logging following these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- Click on the checkbox `Enable logging to file` 
- Confirm the settings panel looks like the screenshot below
- **Restart IINA** to activate logging
![enable-logging](https://github.com/user-attachments/assets/81ca83de-09e4-4938-a4f9-f902c5728b18)

Then reproduce the problem starting IINA fresh and playing one video. Once IINA is not responding use the [Activity Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac) to collect a process sample . To do that 
- Open `Activity Monitor` in `/Applications/Utilities`. 
- Find IINA in the list of processes displayed by the monitor
- Click on IINA in the `Process Name` column to select that process
- Then click on `Sample Process` under the `View` menu
- A panel will appear titled `Sample of IINA`
- Wait for the `Activity Monitor` to finish sampling IINA
- When `Activity Monitor` finishes click on the `Save…` button and save the report to a file
- Drag and drop that file to the `Add a comment` section below
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Click on `Open log directory`
- A new `Finder` window appears containing the logs for this session
- **Quit IINA** to complete the log files
- Drag and drop the `iina.log` and `mpv.log` file to the `Add a comment` section
- Click on the `Comment` button to attach the files to this issue

**DO NOT FORGET** to disable logging once you have obtained log files for the problem. IINA does not restrict the size of log files or delete old logs. If you leave logging enabled the logs will continue to accumulate.

**Comment by jimmyorz** [comment]
[IINA的樣本.txt](https://github.com/user-attachments/files/16370583/IINA.txt)
[iina.log](https://github.com/user-attachments/files/16370584/iina.log)
[mpv.log](https://github.com/user-attachments/files/16370585/mpv.log)

**Comment by PsychoSid** [comment]
fwiw Elmedia is reported to have this issue too, I have had no issues with Movist Pro. Not sure what these do under the covers. 

Pretty sure this will be ironed out by Apple so I can start to use my favourite IINA on this beta again

**Comment by low-batt** [comment]
@PsychoSid @jimmyorz Thank you both for your help with this problem. The report that other players are experiencing problems is very helpful. That other applications are having trouble makes it more of a priority for Apple.

By coincidence @krackers has been helping me make changes in the affected area of IINA. That may be why a nightly build of the `develop` branch is less prone to the problem.

The process sample shows multiple deadlocked threads. The main thread is blocked on a lock inside `CAOpenGLLayer` code:
```text
    +                             2333 CAOpenGLLayer_timer_callback(__CFRunLoopTimer*, void*)  (in QuartzCore) + 176  [0x19bf866d4]
    +                               2333 CAImageQueueCollect_  (in QuartzCore) + 1152  [0x19bee5700]
    +                                 2333 release_images(_CAImageQueue*, CAImageQueueReleased*)  (in QuartzCore) + 452  [0x19bf14fe4]
    +                                   2333 CA::(anonymous namespace)::IOSurface::~IOSurface()  (in QuartzCore) + 24  [0x19bf91060]
    +                                     2333 CA::(anonymous namespace)::IOSurface::~IOSurface()  (in QuartzCore) + 236  [0x19bf91170]
    +                                       2333 delete_buffer(unsigned long, CAImageQueueBuffer*, void*)  (in QuartzCore) + 364  [0x19c15a544]
    +                                         2333 CAImageQueueCommit::CAImageQueueCommit(_CAImageQueue*, CA::GenericContext*)  (in QuartzCore) + 132  [0x19bf09d18]
    +                                           2333 CA::Context::Generic::retain_encoder_cache()  (in QuartzCore) + 32  [0x19bf09d94]
```

The critical IINA `com.colliderli.iina.mpvgl` thread whose job it is to display video frames is blocked on a lock inside of a call to [CATransaction.flush](https://developer.apple.com/documentation/quartzcore/catransaction/1448270-flush):
```text
    +                     2333 ViewLayer.draw(forced:)  (in IINA) + 256  [0x104e360c0]
    +                       2333 @objc ViewLayer.display()  (in IINA) + 24  [0x104e36574]
    +                         2333 ViewLayer.display()  (in IINA) + 244  [0x104e3653c]
    +                           2333 CA::Transaction::commit()  (in QuartzCore) + 648  [0x19bed8f78]
    +                             2333 CA::Context::commit_transaction(CA::Transaction*, double, double*)  (in QuartzCore) + 9604  [0x19c087750]
    +                               2333 _os_unfair_lock_lock_slow  (in libsystem_platform.dylib) + 180  [0x1932b9e4c]
    +                                 2333 __ulock_wait2  (in libsystem_kernel.dylib) + 8  [0x193251c7c]
```

The IINA `com.colliderli.iina.controller` thread whose main job is to read events from mpv is processing a mpv event and blocked on a lock while trying to display a frame:
```text
    +                     2333 MPVController.handleEvent(_:)  (in IINA) + 5528  [0x104ec2ebc]
    +                       2333 PlayerCore.playbackRestarted()  (in IINA) + 264  [0x104e87e00]
    +                         2333 ViewLayer.draw(forced:)  (in IINA) + 256  [0x104e360c0]
    +                           2333 @objc ViewLayer.display()  (in IINA) + 24  [0x104e36574]
    +                             2333 ViewLayer.display()  (in IINA) + 196  [0x104e3650c]
    +                               2333 protocol witness for LockImpl.withLock<A>(_:) in conformance OSUnfairLockImpl  (in IINA) + 20  [0x104e396b4]
    +                                 2333 OSUnfairLockImpl.withLock<A>(_:)  (in IINA) + 64  [0x104e3967c]
```

The critical high priority `CVDisplayLink` thread is also blocked on a lock.

The difference between IINA 1.3.5 and the nightly build of the `develop` branch is that refactoring is in progress to change the  `com.colliderli.iina.controller` thread to queue work to the main thread instead of trying to process events itself to ensure IINA does not allow the mpv event queue to overflow. Could be that changes the timing and just happens to make this problem a little harder to reproduce.

I believe Apple will need to solve this one.

**Comment by vpoguru** [comment]
If it's helpful to give feedback on players who have the same problem, it may also be useful to report players who don't. I found one: [Movist Pro](https://movistprime.com).

**Comment by PsychoSid** [comment]
> If it's helpful to give feedback on players who have the same problem, it may also be useful to report players who don't. I found one: [Movist Pro](https://movistprime.com).

Absolutely agree. I mentioned Movist Pro worked for me https://github.com/iina/iina/issues/5088#issuecomment-2250351218 it's the only one I found that is not affected by this clearly Apple bug.

**Comment by krackers** [comment]
Seems like a core-animation bug/regression then. `CAImageQueueCollect_` is in principle not specific to `CAOpenGLLayer`, but in practice I think CAOpenGLLayer is the main layer type that creates multiple IOSurfaces in this fashion.

In the processes traces, the `mpvgl` thread is basically waiting for `CAImageQueueCollect_` to finish, and then `controller` thread is blocked waiting for `mpvgl` to finish.

It might be worth filing a radar so that Apple is aware of this issue.

**Comment by ongkiii** [comment]
i am also having similar issues with random hanging/freezing, interestingly across IINA, MPV and VLC. there's no particular set time frame when it happens, sometimes it might happen in the 10th second of opening a video, sometimes it might happen after 10 mins. its driving me crazy.

**Comment by krackers** [comment]
@ongkiii Are you using `vo=libmpv` mode in MPV (which uses `CAOpenGLLayer`), or what is now the default, `vo=gpu-next` (which uses a `CAMetalLayer` via moltenvk).

**Comment by low-batt** [comment]
Yes, it definitely would be interesting to know the mpv behavior with and without `gpu-next`.

@ongkiii The nature of the problem has to do with the interaction between [threads](https://en.wikipedia.org/wiki/Thread_(computing)). Threads can run  in parallel. When a thread gets to run on a CPU core is controlled by macOS. This means the timing of when a particular thread gets to run is not consistent and can change based on what else is happening on the Mac. There are coding techniques that impose consistency in the interaction between threads when needed. If done wrong these techniques can result in hangs. Such problems are usually timing related and will vary from run to run of an Application. The behavior you described with the hang sometimes happening right away and sometimes after 10 minutes have passed is typical of such problems.

@krackers On this:
> or what is now the default, vo=gpu-next 

The documentation for the [--vo](https://mpv.io/manual/master/#video-output-drivers-vo) option in the `master` version of the mpv manual still indicates:
> The recommended output driver is `--vo=gpu`, which is the default. 

And [gpu-next](https://mpv.io/manual/master/#video-output-drivers-gpu-next) is still described as "Experimental".

I vaguely recall some recent discussion about changing this, but I don't think `gpu-next` has been made the default?

**Comment by krackers** [comment]
> but I don't think gpu-next has been made the default

Hm you're right, `vo=gpu` is still the default, but `vo=gpu` supports the the `macvk` gpu-context as well. So the situation is that by default as of commit https://github.com/mpv-player/mpv/commit/0e441525cfc2c0d56b6d4a5fc67016d7e29d1b2c it will default to using `vo=gpu` with moltenvk. If the build did not link against moltenvk though then it will fallback to cocoa-cb as before.

**Comment by low-batt** [comment]
Thanks for explaining what that change was all about. I was unaware that `vo=gpu` can now support `macvk`. I've not tried using mpv with MoltenVK/Metal yet. Been waiting for `gpu-next` to be available through the rendering API. I'm going to have to somehow find time to catch up on what mpv has been doing.

**Comment by krackers** [comment]
Fwiw strictly speaking I don't think IINA needs to use the rendering API, it could theoretically use `wid` embedding (passing the pointer of a CAMetalLayer or NSView to mpv and letting it draw into that layer). There was a PR on mpv to support wid embedding with moltenvk, I don't know if it was implemented though. My expectation is that libmpv will _not_ ever support gpu-next because most of the developers seem to not like the design of the render api, and supporting wid embedding would solve most of the major use-cases (at least for osx).

**Comment by low-batt** [comment]
The "Want to work on mpv?" mpv issue lists:
> add a way for libmpv to work with libplacebo/gpu-next

So I've been expecting mpv is still planning on eventually adding support to the rendering API.

At one point in time I looked into `wid` embedding and found a documented restriction that seemed like it would cause it to be unusable for IINA. I just looked around and could not find what it was I read. I could ask the senior developers about it.

**Comment by Coeur** [comment]
I also experienced this regression in macOS 15 beta 4.
- I reproduced the freeze with: iina 1.3.5 Build 141, VLC 3.0.21, QuickTime Player
- I found one app which doesn't freeze: command-line MPV 0.38.0, installed with `brew install mpv`

**Comment by low-batt** [comment]
@Coeur Thanks for that report. I've been hoping for a report of whether or not mpv exhibited this problem. I was expecting to hear that it did not.

Based on the process sample provided by @jimmyorz the problem has to do with coordination of the threads that draw the video image. IINA uses background thread drawing. In the past mpv did as well, but mpv has been changed to only use the main thread. Thread problems such as acquiring locks out of order can't happen when there is only one thread. The disadvantage of using the main thread is that the main thread _must_ be used for drawing UI elements such as the OSC, OSD and other IINA windows. If the work exceeds the capacity of one CPU core then you can get dropped frames and visual stuttering. This difference with mpv came up recently in discussions concerning issue #5038.

**Comment by krackers** [comment]
>In the past mpv did as well, but mpv has been changed to only use the main thread

er if mpv 0.38 was tested, doesn't that mean that the major difference is metal vs caopengllayer, not really any threading issue? The fact that vlc and a bunch of players exhibit issues as well seems to strengthens that. I.e. even you switched IINA to only use a single thread for the draw loop, something in Sequoia causes CAOpenGLLayer to occasionally freeze. 

@Coeur can you see if playing the file on homebrew'd mpv with a flag of `--vo=libmpv` exhibits issue?

The fact that quicktime exhibits it as well is interesting, since as far as I know that doesn't use a CAOpenGLLayer, it probably uses an `AVPlayerLayer` or something I think (have not disassembled it).

**Comment by mufidu** [comment]
Adding to this, I want to report that [Infuse](https://firecore.com/infuse) works fine for me.

**Comment by low-batt** [comment]
@krackers Yes, you are correct. Even though you just explained it I forgot that you don't need to use `gpu-next` for mpv to use MoltenVK/Metal now, it only has to be built with the correct libraries for that to be enabled. I'm not used to that yet.

The process sample suggests the problem is tied to OpenGL. Of course as you noted QuickTime must be using Metal. That QuickTime is having trouble too seems to indicate there is more to the problem than we know. We'd need a process sample of QuickTime when it is hung up for comparison.

Of course this is all an academic discussion. Apple needs to fix this problem. The good news is that if QuickTime is having trouble this should be a priority for Apple to fix. How did beta 4 make it out the door with QuickTime broken?

**Comment by krackers** [comment]
>QuickTime must be using Metal

Well to be more precise, even CAOpenGLLayer uses "metal" in the sense that opengl calls are translated to metal ones. What is the issue is not whether opengl is used, but the precise mechanics of how the CALayer is presented. CAOpenGLLayer draws to a queue of IOSurfaces and presents it. At some point unused images in the queue need to be cleaned up, which is where the freeze occurs. There are actually 2 other ways to draw opengl content on mac, (layer-backed nsopenglview and surface-backed nsopenglview) and they do not allocate a queue so they probably would not suffer from the same issue.

 CAMetalLayer allocates a fixed number of IOSurfaces upfront and just double/triple buffers them, so it does not encounter this issue as Couer confirmed.

I disassembled quicktime and I see it uses `AVPlayerLayer`. Maybe it's possible it too allocates a queue of IOSurfaces so exhibits the same issue.

Btw did you file a radar for this issue yet? Even if they are aware of it I believe issues get prioritized based on # of filed radars so it would be good to report it.

**Comment by Coeur** [comment]
>@Coeur can you see if playing the file on homebrew'd mpv with a flag of --vo=libmpv exhibits issue?

Still no issues with homebrew'd mpv 0.38.0.

I'm actually not reproducing with QuickTime Player anymore: may have been a one time issue only for this player?

On the other hand, iina and VLC are easy to reproduce the freeze.

**Comment by PsychoSid** [comment]
Personally QT works for me without issues and Movist Pro too.

**Comment by krackers** [comment]
>Still no issues with homebrew'd mpv 0.38.0.

That's... surprising. Perhaps my hypothesis is wrong and it is indeed a main-thread vs non main-thread draw issue. VLC uses a non-main thread for drawing also. It also makes me nervous that apple is less likely to fix it because using CAOpenGLLayer in this manner is technically unsupported.

@Coeur if you're able/willing to, could you try building mpv at commit https://github.com/mpv-player/mpv/commit/15c48f3dc122be4b29701355cc48eb63cf8e3029 and the one right before that, to see if the background thread drawing is indeed the culprit?  If you are using homebrew you can set the formula like
```
 head "https://github.com/mpv-player/mpv.git", revision: "15c48f3dc122be4b29701355cc48eb63cf8e3029"
```
and do `--build-from-source`

**Comment by ongkiii** [comment]
> Adding to this, I want to report that [Infuse](https://firecore.com/infuse) works fine for me.

same here, Infuse seems to be the only media player working for me at the moment.

**Comment by jimmyorz** [comment]
Not fixed yet in macOS 15.1 beta (24B5009l)

**Comment by Coeur** [comment]
> If you are using homebrew you can set the formula like

I don't think it would work as easily. Those commits are preceding the ffmpeg compilation fix ([#13659](https://github.com/mpv-player/mpv/pull/13659)).
Anyway, I can build mpv from git sources.
```
meson setup --wipe build
meson compile -C build
TOOLS/osxbundle.py build/mpv
```

My analysis (subject to caution, because it's not always immediate to trigger the issue, so I may have not spent enough time trying):

No video freezes:
- MPV 7758f6f50e103ffecea7f02cf8cc148790b86bb6 with ffmpeg@7 and the build patch https://github.com/mpv-player/mpv/pull/13659/files and also the patch https://github.com/mpv-player/mpv/pull/13665/files (in order to have audio)
- MPV 15c48f3dc122be4b29701355cc48eb63cf8e3029 with ffmpeg@6

Video freezes:
- MPV 7758f6f50e103ffecea7f02cf8cc148790b86bb6 with ffmpeg@6

So, unless I was mistaken in my tests, there are two independent ways to solve the issues:
1. upgrading ffmpeg@6 to ffmpeg@7 (and using patches https://github.com/mpv-player/mpv/pull/13659/files and https://github.com/mpv-player/mpv/pull/13665/files if on old codebase of MPV)
2. or applying the patch that I wrote 2 years ago for macOS 13 beta 5: https://github.com/mpv-player/mpv/pull/10585 and which got included without attribution in https://github.com/mpv-player/mpv/pull/13594

And there is a third way:
3. waiting for Apple to fix it on their end like they did in macOS 13 beta 8, two years ago.

**Comment by low-batt** [comment]
@Coeur Nice analysis! Some quick thoughts…

mpv issue https://github.com/mpv-player/mpv/issues/10276:
> CA_ASSERT_MAIN_THREAD_TRANSACTIONS is set and an implicit transaction wasn't created on a main thread.
abort() called

is already being discussed as part of some work where we are looking into what bug fixes are in mpv that are missing from IINA. This is being discussed in IINA issue #5038. @krackers explains in [this comment](https://github.com/iina/iina/issues/5038#issuecomment-2201161722) addressing this does not require switching to the main queue. The transaction just needs to be made explicit with [begin](https://developer.apple.com/documentation/quartzcore/catransaction/1448282-begin) and [commit](https://developer.apple.com/documentation/quartzcore/catransaction/1448255-commit). It is likely that is how we will address that issue. In other words `CA_ASSERT_MAIN_THREAD_TRANSACTIONS` is a developer debugging tool to catch accidental use of a background thread as _usually_ that is a coding error that was depending upon the automatic [flush](https://developer.apple.com/documentation/quartzcore/catransaction/1448270-flush) performed by the main thread. When using a background thread an explicit transaction is the preferred coding pattern even though an implicit transaction with your own call to [flush](https://developer.apple.com/documentation/quartzcore/catransaction/1448270-flush) works.

I did not find Apple documentation that clearly spells out the intent of `CA_ASSERT_MAIN_THREAD_TRANSACTIONS`. If this was detecting a clear error then you would expect this check to be included as a part of the Xcode [Main Thread Checker](https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early#Detect-improper-UI-updates-on-background-threads). I think it is used to detect a _possible_ error. At least that is my current thinking on this one.

The IINA nightly builds are using mpv 0.38.0 and FFmpeg 7.0.1.

I remember the Ventura freezes. That was worse. The entire window server was locking up. Not sure Apple completely fixed that one. They may have just reduced the window of vulnerability. I have had the window server hang like it did in the Beta a couple of times on this Mac which is still running Ventura. It is rare that this happens.

**Comment by Coeur** [comment]
> The IINA nightly builds are using mpv 0.38.0 and FFmpeg 7.0.1.

Ah, I didn't know there were nightlies. But now I found them at https://iina.io/nightly/ (might be worth mentioning in the readme). I just tried IINA 1db986d0 (mpv v0.38.0-3-g2348fb5e42 FFmpeg 7.0.1) and it freezes, so yes, you'd need extra work for IINA (or cross fingers the macOS 15.0 beta 5 will address it).

**Comment by low-batt** [comment]
With other players hanging I'm hoping this will get Apple's attention and it will be addressed soon.  However from what I recall the Ventura regression was not fixed right away.

**Comment by krackers** [comment]
Thank you for the more detailed investigation.

>upgrading ffmpeg@6 to ffmpeg@7 

This possibly needs more investigation, why would upgrading ffmpeg fix the issue (and that too only for mpv and not iina as you mentioned)? The only thing I can think of is an interaction with hardware decoding. Can you try repeating the test with hardware decoding disabled `--hwdec=no`. Also in both cases were you using `--vo=libmpv`?

**Comment by rafavcc** [comment]
Also having this issue, but I though I was alone. After all, 15.1 is upon us, and the issue is still present.

**Comment by low-batt** [comment]
I had not heard about the release of [macOS Sequoia 15.1 Beta](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes). That seems to be about getting the Apple Intelligence preview into the hands of developers. Yes, it is late in the release cycle for Apple to be introducing regressions into critical areas. That was also the case with Ventura. That was issue #3953. In that case the regression was introduced in Ventura Beta 8 and was not fixed until Beta 10.

I went looking for a VLC bug report and didn't find any mention of Sequoia. Same for Elmedia. That is a bit disturbing.

**Comment by Toffini** [comment]
Seeking seems fixed in Beta 5.

**Comment by PsychoSid** [comment]
Seems OK to me in Beta 5 too. Looks like Apple got around to this one.

**Comment by low-batt** [comment]
@PsychoSid Thank you for reporting this problem. Very helpful that you reported it has been fixed in Beta 5 and closed the issue.

Thanks as well to everyone else who contributed information.

**Comment by zeku2022** [comment]
i am also having similar issues with random hanging/freezing。。15beta1.

**Comment by low-batt** [comment]
@zeku2022 Are you referring to the [macOS Sequoia 15.1 Beta](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes) release? If so, that was released before [macOS 15 Beta 5](https://developer.apple.com/news/releases/?id=08052024d) and could have the same problem as macOS 15 Beta 4.

**Comment by uthiel** [comment]
Fixed in 15.1 b2

**Comment by low-batt** [comment]
@uthiel Excellent news. I was hoping that would be the case. Thanks for reporting it.

**Comment by zeku2022** [comment]
> @zeku2022 Are you referring to the [macOS Sequoia 15.1 Beta](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes) release? If so, that was released before [macOS 15 Beta 5](https://developer.apple.com/news/releases/?id=08052024d) and could have the same problem as macOS 15 Beta 4.
sorry,I mean 15.1 beta1... I have to update to 15.1 beta2..it seems fix it.
