### ISSUE TITLE
Change playback speed delimiter from "," to "." (x1.5)

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [iina/iina#5147]
**What you want IINA to do:**

I want IINA to use speed markings in values such as `1.2` and `1.5` (as opposite to the current `1,2` and `1,5`)

**What IINA does currently:**

The UI uses `.` for the marking beneath the settings (see 0.25x)

![ 2024-08-18 at 01 47 44](https://github.com/user-attachments/assets/c8c65001-5a5c-432e-84f8-9aa9485f4ec0)

**Why you think this should be added:**

I believe it used to be default behaviour of IINA, until on some version I began getting the error bleep when I wrote the more internationally accepted `.` delimiter within a value. I only recently understood that it wasn't a bug, but a behaviour, and that I had to write `1,2` instead of `1.2`. It is my understanding that Americans favor the comma, but just about every app out there that allows changing the speed shows the value using a period (YouTube app, Podcasts on iOS, etc).

**Comment by svobs** [comment]
Seems that we have been been printing decimals wrong in lots of places. Need to use a `NumberFormatter` to properly localize the format and use a comma instead of dot in some locales. See my latest commit in PR #5175.

**Comment by anohren** [comment]
> just about every app out there that allows changing the speed shows the value using a period (YouTube app, Podcasts on iOS, etc).

That's not quite true. This is (or should be) determined by the current locale of the device, and Podcasts for iOS properly respects the user's locale. Here it is with a comma decimal separator:

![IMG_3390](https://github.com/user-attachments/assets/93eb012a-0a78-4887-906c-a394201bb33e)

That YouTube or other apps ignore proper localization isn't a good argument for not doing it. On the other hand, since there are so many sloppy apps out there conditioning people to believe they can't use their own language/number formats, it wouldn't be a bad idea to use a second number formatter with the "lazy dev locale" to catch the instances of people inputting a decimal point when their locale mandates a decimal comma.
