### ISSUE TITLE
Change playback speed up to 5 decimal places

### ISSUE THREAD

**Issue by RoseAF1** [iina/iina#5168]
Is there any way to change the playback speed to 5 decimal places. I am trying to sync a 23.976 fps video to a 25 fps video but i can only alter the speed to 3 decimal places.

**Comment by low-batt** [comment]
25 fps ÷ 23.976 fps = 1.042709376042709 
So the idea is to speed up the 23.976 fps video to 1.042709376042709x to match the 25 fps video?

Clicking on `Show video panel` under the `Video` menu and then pasting `1.042709376042709` into the text field to the right of the slider shows the speed rounded up to `1.043`. Opening the `Playback` menu the speed is shown as `1.04x`.

Checking the mpv log shows IINA setting [speed](https://mpv.io/manual/stable/#options-speed) to a more precise value:
```text
[ 202.090][v][cplayer] Set property: speed=1.042709 -> 1
```

Querying mpv shows the speed was set to that more precise value:
```text
low-batt@gag ~$ echo '{ "command": ["get_property", "speed"] }' | socat - /tmp/mpv-socket | jq
{
  "data": 1.042709,
  "request_id": 0,
  "error": "success"
}
```

Clicking on `Inspector` under the `Window` menu, clicking on the `Status` tab and adding `speed` in the `Watch` section also shows the higher precision setting:
![inspector](https://github.com/user-attachments/assets/ddaa0a58-8195-4cd0-a337-3450227f476f)

_However_ as the speed text field is now displaying `1.043` instead of the actual value of `1.042709` it is easy to accidentally set the speed to the rounded up value. Because of that, this IINA behavior seems wrong to me. I believe IINA should support the same precision for speed that mpv supports. I am going to label this as a defect.
