### ISSUE TITLE
Inaccurate Colorspace handling for SDR/HDR detection

### ISSUE THREAD

**Issue by gnattu** [iina/iina#5200]
**System and IINA version:**

- macOS  15.0.1
- IINA  1.3.5 Build 141

**Expected behavior:**

When opening an SDR video with BT.2020 Color primaries, IINA should display it in an SDR color space and does not trigger HDR mode.

**Actual behavior:**

It displays the SDR video in an HDR Color space.

<details>
<summary><b>Crash report:</b></summary>

```
Not applicable 
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
Not applicable
```
</details>

<br>

**Steps to reproduce:**

- Prepare an SDR video in bt2020 color primaries: `ffmpeg -f lavfi -i testsrc=duration=10:size=1920x1080:rate=30 -pix_fmt yuv420p10le -color_primaries bt2020 -colorspace bt2020_ncl -color_trc bt709 -c:v libx265 -crf 31 -preset superfast -t 10 -tag:v hvc1 testvideo_bt2020_bt2020ncl_bt709_10bit.mp4`
- Open this file in IINA, notice the HDR color space is being used
- Open this file in with MPV `gpu-next` or QuickTime will use SDR colorspace correctly.

- [x] MPV does not have this problem.

**How often does this happen?**

Every time open an SDR video in BT2020 color primaries.

I believe this is due to these lines of code:

https://github.com/iina/iina/blob/66429f771e8eba46376e431865c1eedb88401a47/iina/FFmpegController.m#L615-L622

Having BT.2020 color primaries does not necessarily indicate that the frame is using the PQ transfer function. FFmpeg will flag video frames that use PQ with `AVCOL_TRC_SMPTE2084` in the frame's `color_trc`, alongside the `AVCOL_PRI_BT2020` color primary. Similarly, for the HLG transfer function, FFmpeg will report it as `AVCOL_TRC_ARIB_STD_B67`. Apple also has a corresponding colorspace, `kCGColorSpaceITUR_2020_HLG` for it. Is there any specific compatibility reasons I don't know so that we have to flag all frames using BT.2020 primaries as PQ HDR?

**Comment by low-batt** [comment]
Reproduced for me.

Thank you very much for providing the [FFmpeg](https://ffmpeg.org/) command to generate a test video that exhibits the problem.

The code form `FFmpegController` is from the method `createNSImageWithContentsOfURL`. If enabled, after taking a screenshot IINA will display a preview in the OSD. The development version of IINA contains support for screenshots in [JPEG XL](https://jpeg.org/jpegxl/). The  method `createNSImageWithContentsOfURL` is used when construction of a [NSImage](https://developer.apple.com/documentation/appkit/nsimage) fails due to older versions of macOS not supporting [JPEG XL](https://jpeg.org/jpegxl/) (support was added in macOS Sonoma). There may be problems in this code, but it is not the code that causes IINA to treat a video as HDR. That code is found here:
https://github.com/iina/iina/blob/20f27b70d823e1c7dcb7fafc9d25d41413566be6/iina/VideoView.swift#L441-L476


@CarterLi Thoughts on this issue?

**Comment by CarterLi** [comment]
History: https://github.com/iina/iina/pull/4174

@OceanS2000

**Comment by low-batt** [comment]
@CarterLi Thanks!

I see checking gamma was removed by commit ad8416208a44a83f12d4417e4136f26fb929396b. This has to do with [this comment](https://github.com/iina/iina/pull/4174#issuecomment-1385379209):
> I did some experiments and found that actually mapping everything to PQ seeming to also solve HLG problem. And this approach can avoid the mess for getting mpv output linear values.

@OceanS2000 Thoughts?

**Comment by low-batt** [comment]
As we haven't heard from @OceanS2000 I will look into this.

**Comment by low-batt** [comment]
With the proposed fix IINA will require that videos use a Hybrid Log Gamma or a Perceptual Quantization transfer function to be considered as HDR.

I am concerned about this part of the code:
```swift
// PQ videos will be display as it was, HLG videos will be converted to PQ
mpv.setString(MPVOption.GPURendererOptions.targetTrc, "pq")
```

I tested some HLG videos and they look off compared to mpv. As I was not sure what this was fixing I did not change this.

On the code in `FFmpegController` that @gnattu showed, the feature that is for is currently broken. I will look into this as a part of investigating issue #5212.
