### ISSUE TITLE
nightly icc-profile cb409d60 crashing

### ISSUE THREAD

**Issue by reset131** [iina/iina#5214]
### IINA Version

icc-profile cb409d60

### Release Channel

Release

### macOS Version

12.7.6

### Steps to Reproduce

```text
- IINA would start
- But it will crash when open a video file.
- Tried with different 1080p mov. and .mp4, same result
- I've downgraded to devlope 1a5026a3, with this version is working without issues
```

### Expected Behavior

```text
to not crash
```

### Actual Behavior

```text
crash when open a video file
```

### How often can you reproduce the issue

4 times

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [ ] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by low-batt** [comment]
I believe the problem here is not so much that IINA is crashing, it is that the new [Nightly builds](https://iina.io/nightly/) web page needs to explain that the list of nightly builds now includes builds made from pull requests that have not been reviewed and merged, whereas previously IINA only exposed builds from the `develop` branch.

The `develop` branch contains changes that have been reviewed. Builds from this source code branch should never crash. If you want to test the "latest and greatest" development version of IINA, you want a build from this branch. The web page does not point this out.

Usually builds from branches assocated with pull requests should not crash. However if the pull request is marked as a draft then the changes are not ready to be added to IINA, so problems could be encountered. PR #5213 which uses the `icc-profile` branch was a draft, waiting for a new `libmpv` to be uploaded to our download server with a patch for a mpv issue that causes a crash. Builds obtain copies of the libraries from other projects that IINA is dependent upon from this server using the script `other/download_libs.sh`. The build was from when the pull request was first created, before the new version of `libmpv` was available. I downloaded that build and it crashed for me too.

I forced the build for that PR to run again and generate a new build now that the new version of `libmpv` is available. If you download IINA again from the `icc-profile` branch you will find it is no longer crashing. However, unless you specifically want to test the proposed changes to ICC profile handling, that build is not for you. If you want to try the latest development version of IINA, pick the latest nightly build from the `develop` branch.

@uiryuu I'm thinking the nightly builds web page probably should have separate sections, with one up front for all the builds from `develop` and a separate section for other builds. Or at least point out the difference between these builds.

For the record, I'm expecting this was the crash you encountered:
```text
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1aa588704 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1aa5bfc28 pthread_kill + 288
2   libsystem_c.dylib             	       0x1aa4cdae8 abort + 180
3   libsystem_c.dylib             	       0x1aa4cce44 __assert_rtn + 272
4   libmpv.2.dylib                	       0x1049969c0 ta_free.cold.3 + 36
5   libmpv.2.dylib                	       0x104971940 ta_free + 156
6   libmpv.2.dylib                	       0x104944c60 gl_lcms_set_memory_profile + 64
7   libmpv.2.dylib                	       0x10494cfc8 gl_video_set_icc_profile + 24
8   libmpv.2.dylib                	       0x104945e44 set_parameter + 40
9   IINA                          	       0x1006bf354 specialized Data.InlineSlice.withUnsafeMutableBytes<A>(_:) + 148
10  IINA                          	       0x1006bf1e0 specialized Data._Representation.withUnsafeMutableBytes<A>(_:) + 444
11  IINA                          	       0x1006becdc closure #1 in ViewLayer.setRenderICCProfile(_:) + 264
12  IINA                          	       0x1006beba0 ViewLayer.setRenderICCProfile(_:) + 144
```

**Comment by uiryuu** [comment]
Actually I've already changed the Nightly page to only display commits from develop branch https://github.com/iina/iina-website/pull/78, but the new changes are not deployed...

**Comment by reset131** [comment]
Got it, thank you uiryuu. Got now the latest develop 1a5026a3 running. 
Sorry if I can't offer more details, I'm not a developer, but I want to test these nightly nevertheless and contribute whenever I can.

**Comment by low-batt** [comment]
@reset131 We really appreciate you testing the nightly builds. Very helpful, especially right now as we are down to a handful of issues that we intend to address before cutting the first beta release of the next version of IINA. If you encounter behavior that seems incorrect please do report it.

Don't worry that you are not a developer. It is fine if you can't supply all the information the issue template requests. Explain the issue are well as you can. If there is something about the template that is confusing, please mention that. We are trying to improve it and make it easier for users to fill in.

If I ever use development related terms that you don't understand please ask me to explain what they mean. I'll be happy to explain more.

@uiryuu I just checked the [Nightly builds](https://iina.io/nightly/) page and it has been updated to not show the PR related builds, _but_ the table header does not match up with the columns. There is still a column named "**Branch**".  The column listing usernames is labeled **SHA**, etc..

**Comment by uiryuu** [comment]
@low-batt Probably due to cache from your browser or CDN. Try to access the page in a incognito window.

**Comment by low-batt** [comment]
That was it. Table was fine after clearing browser cache. Hopefully we are using some cache control headers so that pages eventually expire.

As the crash has been addressed I am closing this issue.

**Comment by reset131** [comment]
> @reset131 We really appreciate you testing the nightly builds. Very helpful, especially right now as we are down to a handful of issues that we intend to address before cutting the first beta release of the next version of IINA. If you encounter behavior that seems incorrect please do report it.
> 
> Don't worry that you are not a developer. It is fine if you can't supply all the information the issue template requests. Explain the issue are well as you can. If there is something about the template that is confusing, please mention that. We are trying to improve it and make it easier for users to fill in.
> 
> If I ever use development related terms that you don't understand please ask me to explain what they mean. I'll be happy to explain more.
> 
> @uiryuu I just checked the [Nightly builds](https://iina.io/nightly/) page and it has been updated to not show the PR related builds, _but_ the table header does not match up with the columns. There is still a column named "**Branch**". The column listing usernames is labeled **SHA**, etc..

Thank you for the encouregment, I will do my best.
