### ISSUE TITLE
Saving audio EQ settings

### ISSUE THREAD

**Issue by lhc70000** [iina/iina#525]
- Save audio EQ sets / set as default
- Sync UI with audio filter `@iina_aeq` it it exists

**Comment by GHubbler** [comment]
There is a little improvement as current EQ setting is now remembered per movie, but not global. Unfortunately, there is still no preset or default setting of the EQ possible.
Tested with new iina 0.0.14 Build 45.

**Comment by GHubbler** [comment]
It seems that the equalizer is completely broken since 1.0.0 beta 2 and 1.0.0 beta 3. 
Sliders don't change the sound. Loading presets from beta 1 throws mediocre errors. Moving sliders and trying to save a new presets leaves me with blank text input fields. if I enter anything similar to the old eq-preset it throws - again - weird errors. Btw. the new settings are similar horrible as VLC. Old style hat some kind of mac-feeling and was very uncluttered and neat. New one is just the opposite.
I'm reverting back to beta 1 build 71. It was near to perfect. 
I hope you get the project back on the track because I am really worried about the development in beta 2 and 3.

**Comment by Whatever29** [comment]
I've downloaded IINA 1.01 Build 103 and can't even see an eQualizer anywhere.
I can't write a right syntax to get an eQ work.
Ideally I'd like to use FIR filters (1 per channel) I created for my dedicated audio player. Is there a convolution engine that can be used with IINA? what would be the syntax to trigger it and the the location of the FIR filters?
I know I'm a unworthy old worm asking, but I beg for help
could not find a solution ggogling (but for this syntax : -af equalizer=8:4:-3:-1:0:1:2:3:2:3 that I could duplicate if I knew which were the reference frequencies)

**Comment by GHubbler** [comment]
Started in 2017. Anything new on this?

**Comment by 2V3EvG4LMJFdRe** [comment]
Just not to let it go stale, I'd like this also.

**Comment by ischorr** [comment]
Ditto

**Comment by GHubbler** [comment]
Added this feature request #3821 because it seems a more practical solution with far better usability.
What do you think?

**Comment by 2V3EvG4LMJFdRe** [comment]
One man's problem, another man's... https://github.com/iina/iina/issues/4357

(🤔 wonder why I posted above wanting this a year ago, perhaps I thought it would make devs of IINA create a more specific system for saving settings were you can tick off different things)

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.
