### ISSUE TITLE
Suggestion: add CI system

### ISSUE THREAD

**Issue by xu-cheng** [iina/iina#94]
May I suggest to add CI system into this project?

CI system like [travis](https://travis-ci.org) and other will offer free auto-build, auto-test(not apply yet) and auto-deploy features. You can even use it to make nightly build.

**Comment by HarukaMa** [comment]
Great point, though I'd prefer to have all nightly builds code signed to prevent hiccups from Gatekeeper, and seems getting the developer certificates into Travis is a bit tedious and dangerous if not handled correctly...

**Comment by saagarjha** [comment]
Do we really need signed, nightly builds? We can set up a Travis CI script that runs without code signing for checking commits and pull requests. We already have a relatively rapid release rate anyways. I can whip up a simple Travis CI configuration if @lhc70000 is fine with it (since he'd have to enable the hook, of course).
