### ISSUE TITLE
how do i change the language?

### ISSUE THREAD

**Issue by legendero** [iina/iina#974]
- macOS 10.12.5
- IINA 0.0.12

how do i change the language? i've searched everywhere and i found no option to set it. surely i missed it somehow it has to be.

**Comment by alejx** [comment]
Please change the language of your system.

**Comment by legendero** [comment]
ohh thank you, i'm currently working on Arabic translation, anyone working on it? the translation page says Work in progress but no files are available

**Comment by alejx** [comment]
Someone has claimed that he is willing to translate Arabic but hasn't sent any patches to us till now. I'll check if he is still working on it.
By the way, if you can use Xcode, you should revise the scheme to your language to let Xcode always runs the app in your language instead of changing the system language.

**Comment by legendero** [comment]
> By the way, if you can use Xcode, you should revise the scheme to your language to let Xcode always runs the app in your language instead of changing the system language.

yes thank you it will save me a lot of time

> Someone has claimed that he is willing to translate Arabic but hasn't sent any patches to us till now. I'll check if he is still working on it.

i probably translated close to 60%, i'll stop and wait for your update, thank you.

**Comment by alejx** [comment]
@legendero Sorry for this late reply. It seems that the prior Arabic translator has not contacted us for a long time. So you can continue your work if you want.
